### ISSUE TITLE
Why has the preview become slower from 2014.05?

### ISSUE THREAD

**Issue by CarlosGS** [openscad/openscad#1045]
Hi, I keep trying to use the latest versions of OpenScad but the preview has just become too slow for me.
I am stuck in 2014.05.31 as I need to render quite complex assemblies (https://github.com/carlosgs/Cyclone-PCB-Factory/tree/master/Hardware/CYCLONE_2).
Also, compiling takes longer to finish.

What can be the reason behind this? I have been using OpenScad in quite powerful machines and the preview has gone from a usable ~10fps frame rate for 2014.05.31, to something like 1fps for the latest versions.

Thanks,
Carlos

**Comment by Nathael** [comment]
Hi guys !
Seems the problem is back in OpenSCAD version 2015.03-1 (current debian sid version)

Opening old projects which were rotating/zooming smoothly in preview is now _horribly_ slow.

Any hint ?

I'm trying to test a newer version, but Debian package from nightly build has unmet dependencies for debian SID (package from http://download.opensuse.org/repositories/home:/t-paul/Debian_8.0/)
and I have a problem when trying to build dependencies from git repository using uni-build-dependencies.sh script : 
Building CGAL 4.4 ...
already downloaded..skipping
cp: cannot stat « /opt/openscad/scripts/../tests/FindBoost.cmake »: No such file or directory

find does not find the file in the sources, seems it is no more present.

openscad version info (the slow one) : 

drizzt@drzwork:~$ openscad -v
OpenSCAD version 2015.03-1
drizzt@drzwork:~$ openscad --info
Could not initialize localization.
OpenSCAD Version: 2015.03-1
System information: Linux 4.4.0-rc4-nath-64+ #6 SMP Fri Dec 11 10:22:25 CET 2015 x86_64 Debian GNU/Linux stretch/sid 4 CPUs 7.78 GB RAM
Compiler: GCC "5.2.1 20151028" 64bit
Boost version: 1_58
Eigen version: 3.2.91
CGAL version, kernels: 4.7, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.0
Qt version: 5.5.1
QScintilla version: 2.9.1
MingW build: No
GLib version: 2.46.2
Application Path: /usr/bin
Documents Path: /home/drizzt/.local/share
Resource Path: /usr/bin
User Library Path: /home/drizzt/.local/share/OpenSCAD/libraries
User Config Path: /home/drizzt/.config/OpenSCAD
Backup Path: /home/drizzt/.local/share/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  /home/drizzt/.local/share/OpenSCAD/libraries
  /home/drizzt

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:


GLEW version: 1.13.0
OpenGL Version: 3.0 Mesa 11.0.8
GL Renderer: Gallium 0.4 on NV96
GL Vendor: nouveau
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes
GL context creator: GLX
PNG generator: lodepng
GLX version: 1.4
OS info: Linux 4.4.0-rc4-nath-64+ #6 SMP Fri Dec 11 10:22:25 CET 2015
Machine: x86_64

**Comment by Nathael** [comment]
OK, managed to compile the latest git version using system libs (-dev packages on Debian), 

Got exactly the same behavior with or without the DEBUG define in the Makefile.

Contact if you need more info or tests : nathael dot pajani at ed3l dot fr


$ ./scripts/check-dependencies.sh
depname     minimum     found       OKness      
qt          4.4         5.5.1       OK          
qscintilla2 2.7         2.9.1       OK          
cgal        3.6         4.7         OK          
gmp         5.0         6.1.0       OK          
mpfr        3.0         3.1.3       OK          
boost       1.35        1.58        OK          
opencsg     1.3.2       1.4.        OK          
glew        1.5.4       1.7.0       OK          
eigen       3.0         3.2.92      OK          
glib2       2.0         2.46.2      OK          
fontconfig  2.10        2.11.       OK          
freetype2   2.4         2.6.1       OK          
harfbuzz    0.9.19      1.0.1       OK          
bison       2.4         3.0.4       OK          
flex        2.5.35      2.5.39      OK          
make        3           4.0         OK

**Comment by kintel** [comment]
@Nathael I just fixed the FindBoost issue. Regarding the slow rendering; could you describe the problem a bit more accurately? Does this look like "laggy" mouse behavior, does the model keep moving after you let go of the mouse?

This may be related to a problem with Qt5. We've got some experimental code to attempt to work around this - perhaps you could give it a spin: ```qmake CONFIG+=qopenglwidget```, then make clean and rebuild.

**Comment by Nathael** [comment]
The model moves very VERY slowly and keep moving after I let go the mousse (for up to over one minute if I move the mouse too much at once ...)

I'll give a try to your compile options right now.

**Comment by guysoft** [comment]
Have the same problem, following

**Comment by guysoft** [comment]
Nightly build solves it

**Comment by chrysn** [comment]
in the interest of bi-directional linking, this is tracked in debian as http://bugs.debian.org/80667

**Comment by mballoni** [comment]
For those who are not using nightly builds, whats seems to be the resolution to this error?
 I instaled from the PPA (Ubuntu 16.04) and I have the 2015.03-1.
 However I'm missing on how to install newer versions given that is the one that came with the PPA.

**Comment by kintel** [comment]
@mballoni I suspect this to be a Qt5 bug, which we have worked around in master. The fix will be available in the next release, and until then you either have to build yourself or using the nightly builds.

**Comment by tobia** [comment]
Nightly build solved it for me too. Ubuntu 15.10

@mballoni Just add `deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_16.04/ ./` as an APT source and install `openscad-nightly`

**Comment by theodim** [comment]
The model keeps moving after I let go of the mouse in Debian 8 but not in Debian 9, when compiling the source of the current master (2017-08-01) as well as the latest release (2015.03).
I am referring to this issue:
https://www.youtube.com/watch?v=GidX4dMeD3A
