### ISSUE TITLE
please add commandline option to render design to image

### ISSUE THREAD

**Issue by Harvie** [openscad/openscad#11]
I think it would be usefull to have commandline option that will allow us to non-interactively render scad design to some bitmap image file (also sending image to stdout can be usefull in some cases). note that there should be some way to define angle of view (like ctrl+[0-9] does or exact angle).

THX ;-)

**Comment by Harvie** [comment]
Excuse me, but why was this closed? I can't see any resolution.
Is it possible it was closed accidentaly by github? It seems to me it automaticaly links this to unrelated issues, just because they contain `#11` string...

**Comment by t-paul** [comment]
This was closed 4 years ago, I guess the bitmap export was implemented at that time.

The feature itself is extensively used in the test framework for years now and [documented in the manual](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment), so what's wrong with closing it? If there's some additional feature request, I'd suggest to create a new issue.

**Comment by nophead** [comment]
>t seems to me it automaticaly links this to unrelated issues, just because they contain #11 string...

They are deliberate references to this issue. Each pull request and issue is automatically given a number by GitHub and you can reference them in comments with # as shorthand for the full URL.

**Comment by Harvie** [comment]
@t-paul but it still can't be run without X server...

**Comment by nophead** [comment]
What gives you that impression? It works fine for me without an X server.

**Comment by rewolff** [comment]
```
assurancetourix:~/3d/wormgear> openscad conveyor.scad -o conveyor.png
Compiling design (CSG Products normalization)...
Normalized CSG tree has 20 elements
assurancetourix:~/3d/wormgear> unsetenv DISPLAY
assurancetourix:~/3d/wormgear> openscad conveyor.scad -o conveyor.png
Compiling design (CSG Products normalization)...
Normalized CSG tree has 20 elements
Unable to open a connection to the X server
Can't create OpenGL OffscreenView. Code: -1.
assurancetourix:~/3d/wormgear> 
```

**Comment by t-paul** [comment]
Well, that's what's commonly called complete requirements, I guess :-). @nophead is normally running on Windows I think and there is indeed no X-Server needed. So the topic is platform specific and also as discussed above not simple to solve for the Linux platform (not sure about macOS and if anyone cares for that).

Still the image export feature does exist, works on all platforms and is used by a number of people on Linux servers.

I think it would be nice to remove the need for Xvfb or Xvnc for headless operation but that should go into another ticket and may take a while as it probably needs quite some changes in the display code.

**Comment by Harvie** [comment]
This might solve the issue in the future:

https://www.phoronix.com/scan.php?page=news_item&px=Virtual-KMS-VKMS-Linux-4.19

**Comment by donbright** [comment]
OpenSCAD uses OpenGL to render images. To get OpenGL to render you need a "GL Context" 

Inside the GUI it uses QT toolkit's OpenGL widget to get a GL context.
On the command line, Mac OSX, it uses Cocoa library to make a GL context. Marius created this.
We ported Marius' work to linux(bsd), it uses GLX under X11 to create a GL context.
We also ported it to Windows, which uses WGL to create a GL context.

You do not need a physical GPU to make a GL Context. On linux/bsd the GLX calls are made using a  library called MESA, and you set the environment variable LIBGL_ALWAYS_SOFTWARE=1 you can force it into 'software rendering', where it basically does what a GPU does, but on a normal CPU instead. 

If you do have a GPU, then Mesa will talk to the driver for your GPU. Now, drivers on linux are kind of a nightmare because, unlike most hardware in linux, there are two kinds of drivers in linux for GPU/vidcards. There's open source driver, then there's proprietary driver. You can get open source driver for AMD, but also Proprietary if you want. Intel has open source drivers - alot of them are crap because they crash (google i950 or i915 crash sometime). But they are open source. But Nvidia. Nvidia. People think Linux Torvalds is a mean person for flipping off Nvidia in public and using curse words. Well, I agree.... its a bit uncalled for. however. 

Nvidia doesnt ship open source drivers for linux. They ship binary blobs in packages that try to overlay the linux distro with their own files. As you can imagine, things get bungled up alot, with file naming conventions, automatic updates of the OS, etc etc etc etc. On top of this, Nvidia's proprietary drivers are not actually drivers. Nvidias drivers are actually massive patch/shim jobs for buggy games  coming out of sweatshops where they intimidate people to work 100 hours a week in permanent "death march" programming sessions. Nvidia ships what are essentially game updates out, but they call them drivers.  It is just depressing. But the other point of this paragraph is that.... if it doesnt work on Nvidia drivers, its going to most of the time be a packaging issue, an installation issue, etc. Its not something isolated to one program like OpenSCAD. 

But anyways. All of that, software or hardware rendering, open source or proprietary driver, through MESA, on linux/bsd, that is still using GLX to get an OpenGL Context, which still needs X11. Now, there is a theoretical possibility to get a GL Context without X, that of something called Offscreen Mesa, which is a version of the Mesa GL library, that can render GL calls without X. Unfortunately, Offscreen Mesa has always been a little bit obscure, a bit unintegrated properly into distributions, for example. By default Mesa does not build the Offscreen Mesa version of itself. You have to rebuild the entire Mesa package to make it work. But it gets a bit confused about the naming of the libraries and such. Its not easy. Here is the other thing about OpenGL. OpenGL programs really really depend on a library called GLEW. GLEW has issues with Offscreen Mesa as well.   I have experimented with specially modifying and re-buidling GLEW and Offscreen Mesa to be able to render in OpenSCAD in command line without X. I had it working actually. There was someone who very nicely gave me a login account on an old Sun Sparc machine where i played with this. The problem is that making an experimental working build of openscad, based on highly modified GLEW and Offscreen Mesa, that renders without X is a whole different ballgame than working with several different projects to upstream some weird bizarre set of patches for something that almost nobody cares about. I'm not going to be able to persuade GLEW to re-do it's entire build system, nor Mesa to re-do theirs. for a tiny use case like this. 

There are other ways to get a GL context without GLX on linux/bsd...  but ... they require you to use 'newer' style OpenGL. OpenSCAD's OpenGL is actually largely from CGAL and OpenCSG, and they are both really old. Really old. 

Lastly, OpenGL itself is dying, as Apple has stopped updating/supporting (which means they will likely remove eventually), and the industry is moving to Vulkan. You cannot 'port from OpenGL to Vulkan', you have to write thousands of lines of code to replace OpenGL functions, and then port on top of that, because Vulkan doesnt provide high level operations like OpenGL did. That's probably the only way to survive long term. (Or hope someone writes an 'Old Opengl on top of Vulkan' library). 

@Harvie  VirtualKMS might be helpful, but it is very vague in that phoronix link about what its relationship to OpenGL, or even Vulkan, will be. If it can provide a GL Context without X, then it would be nice. I'm doubting it tho.

**Comment by MichaelAtOz** [comment]
> you set the environment variable LIBGL_ALWAYS_SOFTWARE=1 you can force it into 'software rendering', where it basically does what a GPU does, but on a normal CPU instead.

@donbright does that work on Windows? I'm doing RDP remote desktop and OpenGL is intermittently working.

**Comment by Harvie** [comment]
@donbright can't find the article, but i've read that VKMS is exactly for this. To provide virtual display on headless servers including GPU acceleration. It's made to enable multiple containers/VMs to use GPU.

**Comment by donbright** [comment]
@MichaelAtOz someone, somewhere, a long time ago, posted how to copy Mesa's version of opengl32.dll into the same directory as OpenSCAD, and IIRC, it did allow the enabling of software rendering on Windows (which would be detectably by looking into openscad help/lib info). It was kind of one of those things, since hardly anybody uses it, its not very polished. I have experimented it on a few windows boxes but i think it was hit and miss. (Mesa can use some weird assembly language optimization that is invalid on some CPUs.)

**Comment by Harvie** [comment]
Just for the record, this might be usefull:
https://virgil3d.github.io/

VirGL virtual OpenGL renderer, which allows virtual machines without GPU to run software dependent on opengl acceleration.

**Comment by Harvie** [comment]
@unique1984 But will this work on VM without proper opengl HW?

**Comment by unique1984** [comment]
> @unique1984 But will this work on VM without proper opengl HW?

As far as i tried, virtualbox headless and digitalocean headless machines gave me something. 
Ofcourse these machines have a proper VGA, but just VGA, and standard drivers on Linux kernel, nothing more. It's doing its  job :)

**VirtualBox Debian 10 & With my OpenScadPhpConnector**
glxgears -> 5seconds ~1000fps

![image](https://user-images.githubusercontent.com/3167656/65250634-8a660180-dafe-11e9-8237-e1c437e89015.png)

**VirtualBox Debian 10 Console**
![image](https://user-images.githubusercontent.com/3167656/65251042-49bab800-daff-11e9-8291-d243261fdf31.png)

**DigitalOcean Console (ssh without -X)**
glxgears -> 5seconds ~500fps
![image](https://user-images.githubusercontent.com/3167656/65251320-cd74a480-daff-11e9-88d6-2de3ea3b420e.png)


**Last one is OpenScad's GUI**
*I am not a CAD expert so, sorry for my inexperience *
![image](https://user-images.githubusercontent.com/3167656/65251529-27756a00-db00-11e9-8758-c379e5447ea3.png)
