### ISSUE TITLE
Infinitesimal term

### ISSUE THREAD

**Issue by bgamari** [openscad/openscad#115]
Often while modelling I find myself wanting to refer to infinitesimals to avoid incompletely joined solids. For instance, the following may well result in a non-manifold solid,

```
union() {
    cube(1);
    translate([1,0,0]) cube(1);
}
```

With an infinitesimal (epsilon) term, I could write the following without fear of non-manifold output.

```
union() {
    cube(1);
    translate([1-epsilon,0,0]) cube(1);
}
```

Clearly this would not be a trivial change and would probably require some rather invasive reworking, but I thought I might document the idea regardless.
##

**Comment by ChrisVesters** [comment]
@MichaelAtOz It shouldn't be required to have a variable2 as you call it, because 2 *s should give the exact same result. Although I do understand you may want to have it because you use it all the time.

I'm just not very fond of having too many special variables as it means you need to know the meaning of all of these. By using 2 * s you easily see that it is double the value, with s2 you don't.

**Comment by nophead** [comment]
The epsilon needed to avoid Z fighting also depends on how far the camera is from the surface in question so I don't think it is worth trying to calculate it. I currently use 1/80 so that it is a rational floating point number.

**Comment by MichaelAtOz** [comment]
>  By using 2 * s you easily see that it is double the value, with s2 you don't.

Fare enough, can't hurt to ask...

>(I said) note from #379 "The tolerance is built into OpenGL, and is dependent on object size, GPU, drivers, OS." if this epsilon can be calculated based on these it would be handy.

>(nophead said)  to avoid Z fighting also depends on how far the camera is from the surface in question 

That is the point of calculating it. I have to change the s value depending on the model, it's usually good, but unusual models need a different value. However I have no idea whether this is calculable.
Think of it as a lazy surface, that basically using 's' (or whatever) says if I'm touching another surface it is either jogged into or away from that surface, depending on the operation involved. Just day dreaming...

Anyway, given built in variables can be reassigned, just like $fn (etc) is set to 'reasonable' values, surely a (say) E variable (to be consistent with PI), can have a reasonable value, and if necessary it can be changed by the program.

I think that having it a a feature will, over time, consolidate its use, so everyone understands the E & E*2 concept automatically. ATM people use all sorts of variables and constants.

My 2c worth...

**Comment by nophead** [comment]
It doesn't change directly with the model. It changes due to the viewing distance and you view larger models from further away. So the optimum value would be different in different parts of a scene depending on the camera view. 

I think it would be weird if the geometry of your model changes as you move the view point around. When you make STLS they would change slightly depending on the zoom level. Also people would get difference STLs on difference graphics hardware.

I use eps = 1/80 for modelling for 3D printing but if I model a whole machine and zoom out a bit some Z fighting will become visible. It is a personal preference. I don't think it can really be calculated.

**Comment by t-paul** [comment]
If there ever is agreement on what value to set in existing models, we could add that. But so for it's probably better to just leave that to the specific model (e.g. as `$eps = 1/80;` once in the top level file).
