### ISSUE TITLE
2D shapes with F6 don't render at z = 0

### ISSUE THREAD

**Issue by atartanian** [openscad/openscad#1202]
2D shapes rendered with F6 appear below the z = 0 plane
![screen shot 2015-02-02 at 12 25 59 pm](https://cloud.githubusercontent.com/assets/1625877/6005236/bac3af1a-aad6-11e4-9569-2a203dcdc2c2.png)

**Comment by kintel** [comment]
I don't remember why we did that. If nobody remembers, we might just move them to 0 again :)

**Comment by hroncok** [comment]
And the daemons will come back :D

**Comment by MichaelAtOz** [comment]
A slight tangent, but perhaps this is also the time to make the F5 z-height/thickness 0.001 or such. Noting confusion that comes up in the forum from time to time.

**Comment by TakeItAndRun** [comment]
+1

2015-03-13 23:37 GMT+01:00 Michael <notifications@github.com>:

> A slight tangent, but perhaps this is also the time to make the F5
> z-height/thickness 0.001 or such. Noting confusion that comes up in the
> forum from time to time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openscad/openscad/issues/1202#issuecomment-79496998>.
>



-- 
stempeldergeschichte@googlemail.com <karsten@rohrbach.de>

P.S. Falls meine E-Mail kürzer ausfällt als Dir angenehm ist:
Ich probiere gerade aus kurze Antworten statt gar keine Antworten zu
schreiben.
Wenn Du gerne mehr lesen möchtest, dann lass es mich bitte wissen.

P.S. In case my e-mail is shorter than you enjoy:
I am currently trying short replies instead of no replies at all.
Please let me know, if you like to read more.

Enjoy!

**Comment by MichaelAtOz** [comment]
> A slight tangent, but perhaps this is also the time to make the F5 z-height/thickness 0.001 or such. Noting confusion that comes up in the forum from time to time.

Should I raise another issue for this?

**Comment by kintel** [comment]
@MichaelAtOz Please do - would be good to keep track of that.
