### ISSUE TITLE
virtualfb.sh uses incompatible Xvnc in presence of Xvfb

### ISSUE THREAD

**Issue by chrysn** [openscad/openscad#1542]
virtualfb.sh uses the presence of an Xvnc and Xvfb binaries to choose which server to use, and prefers Xvnc, then invokes both as `${VFB_BINARY} :${DISPLAYNUMBER} -screen 0 800x600x24`.

this has so far always worked for me with Xvfb, but with Xvnc, the -screen argument is unknown, causing the tests to fail.

i can work around this by ensuring that Xvnc is not installed, but this should be made more robust. if there are different versions (as in version numbers or different vendors) of Xvnc (which i vaguely remember, yet only find one inside debian) of which only some work, please consider checking for the variety. if that is unfeasible or the issue is just an oddly unsupported feature of the Xvnc i'm using (realvnc's [vnc4server](https://packages.debian.org/sid/vnc4server)), please consider switching the sequence of the checks to use Xvfb in the presence of both (there seems to be less variety there). if there is no current Xvnc with which this can work and the issue has gone undetected for longer, i'd suggest dropping xvnc support from virtualfb.sh altogether.

**Comment by donbright** [comment]
thanks very much for the bug report

fixed in 95fc916d7850169c3faaf7d87b404d60a51530c2

default to prefer Xvfb

use different options to Xvnc based on http://www.tightvnc.com/Xvnc.1.php and https://www.realvnc.com/docs/man/vncserver-virtual.html

(the only reason Xvnc is there is because one of the GNU Compile Farm test boxes  only had Xvnc installed)
