### ISSUE TITLE
Double-click to center not working when compiled against Qt5

### ISSUE THREAD

**Issue by nairaner** [openscad/openscad#1787]
In Qt5 after frame is render framebuffer is switched to output frame. For finding new view port after double-click we use glReadPixels with Depth buffer which in qt5 is empty
![image](https://cloud.githubusercontent.com/assets/7582653/18421724/3c583422-7891-11e6-891e-264494f2799c.png)

**Comment by superkartoffel** [comment]
I can confirm this issue. Even worse, I get a GLError 1282 from the glReadPixels call. It's probably because I'm on archlinux which uses wayland instead of xorg as default. I'm willing to admin that this might be a driver issue, so I'm not filing a new bug here.
Using xorg, I get z=1 and therefore still doesnt work. 

Any suggestion how to fix this?

**Comment by AttentionalM** [comment]
Still an issue on Mac OS X (10.11) compiled using Qt version 5.7.0 from scratch on 28/08/2017
