### ISSUE TITLE
Customizer: Don't scan for parameters in included files

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1840]
Fix handling of includes, those should not be scanned for parameters (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18761))

(moved from #1781)

**Comment by amarjeetkapoor1** [comment]
Any idea on how to solve this issue. Only solution that is coming to my mind is that we keep the name of file like the location is stored for each node (might be usefull for long run) or simply store a boolean to tell whether its from from included file or not to make customizer behave like that of Thingiverse. Otherwise, The behavior is somewhat correct (50%) as it's meant to behave like if part of main file.

**Comment by MichaelPFrey** [comment]
Currently, parameters from includes get either no or the wrong description:

![error](https://user-images.githubusercontent.com/24962768/36644903-2c1cb240-1a61-11e8-977b-f95b3cb1826a.png)

tricky situation

**Comment by amarjeetkapoor1** [comment]
#2044 Could solve this BUT there is a problem attached.
Which would be solved easily by increasing stack size that wouldn't be a viable solution but not good one and another one would require some extra work.
