### ISSUE TITLE
Feature request - When Editor Pane hidden add Export STL Icon to preview icon list [$10]

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1900]
Or just add it regardless.
When working with an external editor I miss the convenience of the export icon, on the now hidden editor pane.

[$10 Bounty](https://www.bountysource.com/issues/40462106-feature-request-when-editor-pane-hidden-add-export-stl-icon-to-preview-icon-list)

**Comment by kintel** [comment]
The preview icon list is a bit long. Perhaps a good opportunity to look into compressing it a bit.
..perhaps by using some sort of drop-down icon selector on the view angle icons? Not sure how annoying that is to implement in Qt..

**Comment by MichaelAtOz** [comment]
BTW, I had a narrow window and noticed when the Icon bar is cut short, presumably Qt, makes an icon drop-down menu. Perhaps there is a wraparound option - ie get two lines of icons.
![icon menu](https://cloud.githubusercontent.com/assets/1972961/26572190/6411f4f6-455c-11e7-8daf-95a327d93e31.PNG)
(couldn't easily capture with the menu showing)

So maybe more icons are OK?
I think the order will be important tho.

**Comment by Sharma-Hrishabh** [comment]
Tried to do this. As it is a GUI update, feedback will be very helpful :)

**Comment by t-paul** [comment]
I would prefer having the toolbars user customizable instead of dynamic, but I guess that may still take a while. So let's have this solution now and see how it goes :smile:.

@Sharma-Hrishabh you should be able to claim the bounty on bounty source now (see link in the issue description). Although it seems their site has some trouble at the moment.
