### ISSUE TITLE
Feature Tweak - Line marker numbering

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2020]
I seem to frequently have the scale marker numbers not showing on the visible preview window.
For example from this:
![scale small](https://cloud.githubusercontent.com/assets/1972961/25571294/92dd764a-2e71-11e7-9084-7b0836b9852e.PNG)
One scroll wheel notch gives me this:
![scale one step](https://cloud.githubusercontent.com/assets/1972961/25571298/a2ddc41e-2e71-11e7-8bf6-abce3d8a0ed0.PNG)

One possibility would be to have an intermediate stage where every 2nd mark is numbered. 

[$15 Bounty](https://www.bountysource.com/issues/44706972-feature-tweak-line-marker-numbering)

**Comment by DMCShep** [comment]
Screenshot 1 is at the closer zoom where every 10 units are labeled. Screenshot 2 is at the further zoom where every 100 units are labeled (you'd see the 100 labels if you panned a bit). Every ten marks shows a number. Took some screenshots of a guitar nut I just made demonstrating this.

Zoomed in to label every ten:
![10 zoom](https://user-images.githubusercontent.com/20283733/29479034-f97ee682-843d-11e7-978c-aa8dda0769e1.png)

One click out to label every hundred:
![100 zoom](https://user-images.githubusercontent.com/20283733/29479045-0e03868a-843e-11e7-92f3-e4e267900ef5.png)

Panning to show said label:
![100 zoom shift](https://user-images.githubusercontent.com/20283733/29479054-17638464-843e-11e7-84ac-d6d285c59edc.png)

**Comment by MichaelAtOz** [comment]
@DMCShep was that to just confirm the behaviour?

**Comment by DMCShep** [comment]
Oops, thought the bug was the lack of any label, rather than it not being visible in the viewport.

In any case, detection of when the marks need to change scale should probably be independent of when the labels need to change scale. Wouldn't hurt to consider labels at every 10, 20, 50, 100, etc. units either.

**Comment by MichaelAtOz** [comment]
This is a feature request. Could maybe a bug, but basically it was not helpful & I wanted to spend some bounty money on an annoying thing.

**Comment by thehans** [comment]
I like the improved labeling scheme from @justbuchanan , but I have a suggestion to improve it further.

So the issue was mainly the size of the "jump" that the labels scale by was too large.

Originally it was a single jump * 10 for every decimal power.

So if are viewing a `cube(1);`  you start zoomed in enough to see single unit labels: 
1,2,3,4,5,...  then you start to zoom out ... and eventually the labels jump * 10 to =>
10,20,30,40,50,... and * 10 again, every time the label interval changes => 
100,200,300,400,500,...

With the latest changes, we now have effectively have two steps for each factor of 10.  first *2, then *5
1,2,3,4,5,...       * 2 => 
2,4,6,8,10,...      * 5 =>
10,20,30,40,50,...  repeat
So now the biggest jump we see is going from counting by twos to counting by tens: We've reduced that maximum jump in half from *10 to *5 

If we add in a third step of counting by fives (and maybe a corresponding medium tick size?) then that maximum jump can be divided in half again *2.5, which is more consistent with *2 jump of the other two steps now.
1,2,3,4,5,...  counting by ones     *2 => 
2,4,6,8,10,...counting by twos    *2.5 => 
5,10,15,20,25,... counting by fives *2 => 
10,20,30,40,50,... repeat

**Comment by kintel** [comment]
I don't have a strong opinion - perhaps implement it (or a general mechanism for tuning it) and see if it feels better?

**Comment by thehans** [comment]
I did a little more testing of the current code and found one issue in particular that I think should be addressed:
Zooming in beyond 0.2 label interval jumps to 0.02 (no "counting by ones" step), resulting in a lot of overlap and illegibility.  This gif shows a the difference between a single zoom step:
![axis_labels_small](https://user-images.githubusercontent.com/252233/32200136-184baf84-bd9e-11e7-942f-445989e420bd.gif)

Also this is less severe, but I figured I'd mention the other worst case for the current labeling, which could potentially be alleviated with another labeling "step" as I mentioned in prev. post:
Zooming out to where label interval = 200000 can get crowded enough that labels flow together, and where the label interval beyond that is just out of frame.
![axis_labels_large](https://user-images.githubusercontent.com/252233/32200072-bd379a9a-bd9d-11e7-9bc8-997176787658.gif)

I don't have a better implementation worked out yet, I could give it a shot, but I figured @justbuchanan gets first dibs if they want to take a crack at the problem. :)

**Comment by justbuchanan** [comment]
@thehans, thanks for pointing that out, it's pretty unreadable. I just sent https://github.com/openscad/openscad/pull/2170 to fix this and it seems to work well. Please give it a shot and let me know if you see anything else.

**Comment by justbuchanan** [comment]
Here's a quick test of adding labels every 5 tick marks: https://github.com/justbuchanan/openscad/tree/more-labels. You may be able to tune the thresholds better - I only adjusted them a little bit.

I think the overlapping labels for large numbers can also be fixed by adjusting the thresholds. There seems to be a bad zoom range when the numbers are large, but not large enough to switch to scientific notation. I'll play around with this some more.

Also, would there be any opposition to changing the font used for the numbers? I find the current one a little tough to read, especially because of the underscores used as decimal points.

**Comment by thehans** [comment]
The challenge with changing the "font" is that all the characters are currently a bunch of hardcoded vertex data drawn as GL_LINES if I remember correctly.  Maybe it could be re-implemented to display a bitmapped font instead?

I think ideally the labeling and tick marks would be rendered directly by a fragment shader.

**Comment by MichaelAtOz** [comment]
[KISS](https://en.wikipedia.org/wiki/KISS_principle)

**Comment by kintel** [comment]
As Michael pointed out, this was optimized for developer time and to limit the number of dependencies.
One of the thing on the long-term TODO list is to rewrite the rendering infrastructure, perhaps into using some rendering/OpenGL framework. Once that's in place, such a framework may have support for font rendering, which would make this easier on us.

**Comment by thehans** [comment]
Found another issue, the digits on the Z positive axis are in reverse order

![z_positive_axis_label](https://user-images.githubusercontent.com/252233/32419005-e91411d0-c238-11e7-8cbd-d1eb5105cfba.png)

**Comment by justbuchanan** [comment]
I think you're right that the backwards numbering on the +z axis was that way before. Now that you've point it out, it looks obvious - I'm surprised I didn't notice it before.

I'm away from my dev computer right now, so I can't test this, but I suspect changing this line from  `di>0` to `di>=0` would fix it: https://github.com/openscad/openscad/blob/master/src/GLView.cc#L705. I can try it out later tonight or tomorrow.

**Comment by justbuchanan** [comment]
I sent a fix for the backwards labeling for the z axis in #2186.

Also, +1 to your suggestion about the labeling on the y axis.

**Comment by MichaelAtOz** [comment]
Is this fixed? @justbuchanan want to claim the bounty?

**Comment by justbuchanan** [comment]
Hi @MichaelAtOz, sorry for the slow response, this message slipped past me. But yes, that would be great! I believe this is fully-implemented and working well.

**Comment by MichaelAtOz** [comment]
Closing. @justbuchanan you can claim the bounty [here](https://www.bountysource.com/issues/44706972-feature-tweak-line-marker-numbering), let me know how it goes, as they have new owners.
