### ISSUE TITLE
display bug with difference and polyhedron

### ISSUE THREAD

**Issue by charlyoleg** [openscad/openscad#228]
In particular condition, faces of the polyhedron becomes transparent. The bug appears when we remove a cylinder to a polyhedron (with difference) and a face of the cylinder is exactly on a edge of the polyhedron.

```
// openscad_bug_charlyoleg.scad
//
// openscad display bug
// reported by charlyoleg
// on 2012/12/11
//
// openscad version: OpenSCAD 2012.05.12
//
// bug description:
// in particular condition, faces of the polyhedron becomes transparent
// The bug appears when we remove a cylinder to a polyhedron (with difference) and a face of the cylinder is exactly on a edge of the polyhedron.
// check lines 115 and 116 of this file



module sub_vertical_trapeze(bottom_a, bottom_b, bottom_c, bottom_d, top_a, top_b, top_c, top_d){
  polyhedron(
    points = [
      bottom_a,
      bottom_b,
      bottom_c,
      bottom_d,
      top_a,
      top_b,
      top_c,
      top_d],
    triangles=[
      [0,1,2], [2,3,0],
      [1,0,4], [4,5,1],
      [2,1,5], [5,6,2],
      [3,2,6], [6,7,3],
      [0,3,7], [7,4,0],
      [4,7,6], [4,6,5]],
    convexity=30);
}

module check_sub_vertical_trapeze(){
  ba = [2,2,1];
  bb = [2,-1,1];
  bc = [-3,-5,1];
  bd = [-1,3,1];
  ta = [3,4,3];
  tb = [3,-2,3];
  tc = [-4,-4,3];
  td = [-3,2,3];
  sub_vertical_trapeze(ba, bb, bc, bd, ta, tb, tc, td);
}
//check_sub_vertical_trapeze();

module vertical_trapeze_square(bottom, top){
  bx = abs(bottom[0]);
  by = abs(bottom[1]);
  bz = bottom[2];
  tx = abs(top[0]);
  ty = abs(top[1]);
  tz = top[2];
  ba = [  bx,  by, bz];
  bb = [  bx, -by, bz];
  bc = [ -bx, -by, bz];
  bd = [ -bx,  by, bz];
  ta = [  tx,  ty, tz];
  tb = [  tx, -ty, tz];
  tc = [ -tx, -ty, tz];
  td = [ -tx,  ty, tz];
  sub_vertical_trapeze(ba, bb, bc, bd, ta, tb, tc, td);
}

module vertical_trapeze_square_half(bottom, top){
  bx = abs(bottom[0]);
  by = abs(bottom[1]);
  bz = bottom[2];
  tx = abs(top[0]);
  ty = abs(top[1]);
  tz = top[2];
  ba = [  bx,  by, bz];
  bb = [  bx, -by, bz];
  bc = [   0, -by, bz];
  bd = [   0,  by, bz];
  ta = [  tx,  ty, tz];
  tb = [  tx, -ty, tz];
  tc = [   0, -ty, tz];
  td = [   0,  ty, tz];
  sub_vertical_trapeze(ba, bb, bc, bd, ta, tb, tc, td);
}

module vertical_trapeze_square_quater(bottom, top){
  bx = abs(bottom[0]);
  by = abs(bottom[1]);
  bz = bottom[2];
  tx = abs(top[0]);
  ty = abs(top[1]);
  tz = top[2];
  ba = [  bx,  by, bz];
  bb = [  bx,   0, bz];
  bc = [   0,   0, bz];
  bd = [   0,  by, bz];
  ta = [  tx,  ty, tz];
  tb = [  tx,   0, tz];
  tc = [   0,   0, tz];
  td = [   0,  ty, tz];
  sub_vertical_trapeze(ba, bb, bc, bd, ta, tb, tc, td);
}

module check_vertical_trapeze_square(){
  vertical_trapeze_square([3,2,1], [2,3,3]);
  vertical_trapeze_square_half([3,2,6], [2,3,8]);
  vertical_trapeze_square_quater([3,2,11], [2,3,12]);
  vertical_trapeze_square([3,2,16], [2,3,15]);  // Yahoo! The top face can be bellow the bottom face!
}
//check_vertical_trapeze_square();

module arm_for_print(){
  difference(){
    union(){
      vertical_trapeze_square_half([10, 10, 0], [5, 10, 30]);
    }
    union(){
      //translate([2,0,35]) // no bug
      translate([5,0,35])   // bug: the some polyhedron faces are transparent!
      rotate([0,90,0])
        cylinder(r = 10, h = 10, center = false);
    }
  }
}
arm_for_print();
```

**Comment by dratasich** [comment]
Update:
**Clockwise** (when looking from outside inwards) is preferred now.
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Primitive_Solids#polyhedron
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Primitive_Solids#Debugging_polyhedrons

**Comment by nophead** [comment]
How can this have changed, it would break all existing code?

**Comment by Ma-XX-oN** [comment]
Hasn't it always been "preferred"?

**Comment by nophead** [comment]
Preferred is the wrong word. The winding order determines which side of the
face points out. If you do them all the wrong way you get a negative
volume. If you want to make a hollow solid the inside needs to be a
negative volume.

**Comment by donbright** [comment]
the OpenGL rendering also changed a lot since 2012, perhaps the ThrownTogether colors have been thrown backwards during that migration? 

i would like to see some more examples of old vs new and some proof. because it could be seen as a flaw in the regression test suite for ThrownTogether renderer, if this was missed. 

but there is a different possibility. it might be because polyhedron() code was modified alot to deal with faces that had more than 3 points.  in fact somewhere someone reported they could build incomplete meshes now thanks to weirdness of CGAL construction... i cant remember the issue # but i remember looking into the guts of CGAL.  IIRC part of the OpenSCAD codepaths are technically geometrically backwards now in certain situations but it did not break things.  i think maybe because for many situations, when everything is backwards in exactly the same way, it is not distinguishable from everything being frontwards. as an example, when exporting STL without normals, it would not be noticeable to most situations whether you have all your faces backwards or not.
