### ISSUE TITLE
Can anything be done about the rendering speed?

### ISSUE THREAD

**Issue by thecrazy** [openscad/openscad#237]
From what I understand solidwork uses cgal and isnt this slow redering.

Is there anything that could be done to speed things up? is cgal multithreaded?

**Comment by michaeledi** [comment]
CGAL indeed has slow speed while processing the complex models such as image surface, would be great if there's any way to speed that up!

**Comment by MichaelAtOz** [comment]
@michaeledi Wow! Resurrect a 3.5 year old thread. 
Get a faster PC?

**Comment by michaeledi** [comment]
@MichaelAtOz Well...Didn't see the time, I used an i7 processor and Quadro K GPU with 16GB RAM, isn't that "enough"? But the fact is, it still took me 1.5 minute to render a lithopane model with image surface...

The only way I figured out is to open multiple scad programs and click F6 for each of them...

**Comment by t-paul** [comment]
As image surfaces tend to create a huge amount of vertices, they are quite a worst case scenario for CSG operations. Even OpenSCAD side multi-thread calculation would not help as it's single operations that will be slow. So I guess the only options are optimizations in libCGAL (which does not seem to happen) or switching to some other library (which can cause other issues as explained above). To my knowledge there's nobody working on that except some experiments that did not go very far.

Maybe there's a 3rd option specifically for surface though, if we could find some algorithm to generate the surface mesh with less vertices. Depending on the input data, that could help reducing the calculation time, but I don't know if that would be good enough to really make a difference.

**Comment by MichaelAtOz** [comment]
> But the fact is, it still took me 1.5 minute to render a lithopane

[Luxury...](http://www.davidpbrown.co.uk/jokes/monty-python-four-yorkshiremen.html)

I've had 20 hour renders....

...when I grew up we didn't have preview, "But you know, we were happy in those days, though we were poor."...

**Comment by MichaelAtOz** [comment]
@michaeledi BTW, unfortunately ATM, GPU doesn't help with rendering.

**Comment by michaeledi** [comment]
@MichaelAtOz  Haha, that really relieves me a lot XD! So it seems not that annoying waiting for couple minutes!

**Comment by michaeledi** [comment]
@t-paul Thanks for the answer! And do you think OpenJSCAD will render the image faster?

**Comment by t-paul** [comment]
I think it has faster unions, but I'm not sure it supports `surface()`, I've never really used it. Maybe just give it a try...

**Comment by Brasshopper** [comment]
So I am trying to generate a ring fan mount for 3D printing.  I decided to do it by generating a torus with a slit in it by using rotate extrude.  So I have a circle hollowed by a smaller circle, This hollow circle has a slot cut into it and this is what is fed to rotate-extrude to make the ring.  This is attached to a trapezoidal pyramid, hollow, of course, and that is attached to a couple other objects.

At some point, I fell through the rabbit hole.  I am now waiting several minutes simply for making small changes to the viewport.  It claims that it does a preview in a couple seconds - but then you can't see the preview, nor can you really use the program at all.   I find that it is not usable.  I have made sure it has a couple gig memory free, I have not that powerful of a PC, it is an old laptop, but I found a best buy that allowed me to install openSCAD on a floor model and do a render there and it seemed not to be much faster.

openSCAD simply stopped responding.  I restarted the code and the first thing I did was to parameterize out the rotate extrude - and performance went back to normal.

So, is there something I can do?  A trick - maybe?  Should I do the rotate-extrude and extrude a solid and then cut it with a different rotate-extrude rather than doing the complex hollow shape?

**Comment by t-paul** [comment]
There is no trick. Some general suggestions are:

- Don't make the model extremely detailed with huge amount of vertices by using things like `$fn = 200;` - try maybe `$fa = 5; $fs = 0.5` - smaller values will increase detail.
- Use latest version (for Linux there is an issue when using a certain combination of dependencies) - maybe also try the nightly build.

**Comment by thehans** [comment]
In general, for best performance you should do as much operations as
possible in 2D, and only rotate_extrude or linear_extrude after all that is
worked out.  Adding that 3rd dimension greatly increases complexity, its
best to minimize the number of operations done on 3d shapes.

If you can think of a way to reduce the number of difference or
intersection operations, that can also help quite a bit.  When you start
nesting many of those CSG operations inside one another, due to the way the
preview rendering works the number of objects in the CSG tree can explode
to .unmanagable levels.

If you want to trade off slower time to compute the preview for faster FPS
when rotating/panning around in the preview, then try using render(
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/CSG_Modelling#render )
on some of the computationally difficult bits.

If you can post the code you're working with, there might be some more
specific tips we can give.

**Comment by Brasshopper** [comment]
OK, I feel dumb.  The simple answer was to change the $fn to something really low for testing and previews and then to make it a high number for the final render.  I didn't realize exactly how expensive a high $fn was.  $fn=8 is likely good enough to see relationships of shapes and to get rotations and cuts right.

Something I read here caused me to read something else and then I was able to figure this out.  Well, sorry to bother folks.  $fn=8 is the trick that allows me to preview correctly.

**Comment by nophead** [comment]
It is better to set $fa and $fs as Torsten suggested rather than fixing all
curves to be octagons. It then adapts to the size of the shape. $fa = 5;
$fs = 0.5 is suitable for 3D printing viscous plastic like ABS because it
acts like a French curve. You might want $fa a bit lower for PLA when doing
a final render.
