### ISSUE TITLE
Feature Request: View All - default zoom distance

### ISSUE THREAD

**Issue by korpx** [openscad/openscad#2386]
When using "View All" the the view is zoomed out quite a bit with lots of empty space around the object. I find myself zooming in just about every time I've used the function.

Would it be possible to make View All a bit smarter, like if you use View All, and then zoom in, OpenSCAD will keep track of the zoom level the object-to-view ratio and use the same ratio in "View All" operations to follow, naturally adapting to any dimensional changes in the object.

An option for the user to change the zoom level statically would be another, though less smart way I guess.

**Comment by t-paul** [comment]
I don't think it's generally possible to guess what the user meant by just looking at some zoom changes after a button press for some time.
Maybe the calculation for View All is just off a bit and needs to be fixed?

**Comment by MichaelAtOz** [comment]
> Maybe the calculation for View All is just off a bit and needs to be fixed?

Yep. At least on Windows, I'm wondering if it is platform specific. @korpx what platform?

This is Example logo.scad, from there I pressed Zoom+ three times to get to where I would expect View-All to do.
![view-all zoom](https://user-images.githubusercontent.com/1972961/39121162-4d2d7856-46e0-11e8-851b-76b1ac74c9ab.JPG)

**Comment by nophead** [comment]
It seems buggy. If you do cube() it is out by  a factor of about 2. If you do cube(center = true) it is about right.

**Comment by korpx** [comment]
I confirm. A basic test of View All gives different zoom for this cube;

cube([10,10,10],center=false);
vs
cube([10,10,10],center=true);

**Comment by nophead** [comment]
The code gets the bounding box of the scene and ensures a sphere through its corners is in view. There is a bug which makes the distance too big unless the boding box is centred on the origin.

Even with that bug fixed it is far from ideal. If your object is actually a cube parallel to the axes it will be at a distance that ensures it is visible in any orientation. It is too pessimistic for other shapes, even a rotated cube, because a sphere through the bounding box is larger than a bounding sphere in general.  Even a bounding sphere doesn't take into account favourable rotations. For example a tall poll looking from the top.

**Comment by nophead** [comment]
I fixed the bug in this PR https://github.com/openscad/openscad/pull/2472 so the position of objects no longer affects viewing distance. Typically that seems to make it about twice as big because my objects are rarely centred on the origin. They usually sit on the XY plane and often in the positive quadrant.
