### ISSUE TITLE
Edit/Find starts immediate search

### ISSUE THREAD

**Issue by thomaskilian** [openscad/openscad#2440]
I have a very annoying issue with the implementation of the Find command. Here are the steps

- in some file open the Find with CMD-F and
- type the text you want to search and it will find it (nice so far).
- Now close the Find with the button to the right ("Fertig" in German, probably "Ready" in English) and it will close the Find window.
- Place the cursor to some other position (e.g. on the next page of your document).
- Now when you press CMD-F it will jump right to the next occurrence of the previous Find.

This is very annoying (because I intend to search from the current cursor position). CMD-F should only open the Find window and not perform a find by itself. This should only start on a CMD-G. Or after pressing the Next button in the Find window.

**Comment by MichaelPFrey** [comment]
looks like a side effect of:
```
void MainWindow::showFind()
{
	this->findInputField->setFindCount(editor->resetFindIndicators(this->findInputField->text()));
```
in `mainwin.cc`. When clickingon "done" ("Fertig" in German), it also searches again due to basically the same side effect:
```
void MainWindow::hideFind()
{
	find_panel->hide();
	this->findInputField->setFindCount(editor->resetFindIndicators(this->findInputField->text(), false));
```
now we are getting somewhere:
```
int ScintillaEditor::resetFindIndicators(const QString &findText, bool visibility)
{
    ...
    qsci->findFirst(findText, false, false, false, true, true, savelineFrom, saveindexFrom);
    return findwordcount;
}
```
Well, `resetFindIndicators` is not the ideal name. It not only updates the find indicators, it also finds the first word and it return the number of finds. I think that resetFindIndicators should be renamed.
A boolean could be added for "findFirst"/"selectFirst" with a default value (true or false depends on the function name). Alternatively, the find first could become its own function.
