### ISSUE TITLE
Create a system variable $firstpreview

### ISSUE THREAD

**Issue by PRouzeau** [openscad/openscad#2470]
Creation of a variable $firstpreview

This allow to make specific stuff at first preview :
*Define a given camera position
*Some demo

Default zoom of OpenSCAD is rarely correct for a demo.
So I did impose the camera position at execution for first preview.
Though, it is quite problematic because it will reposition the view each time you run, which is rarely desirable.
So, in my applications, I set in the instructions to first go the the [Camera] tab in customizer and untick the variable ‘dictate camera position’ which will free the camera. 
Not very nice for a start of the user manual.
I think the simplest solution is to identify the first preview as specific with a system variable, only true during the first preview.
Image is an extract of the manual of 'protected crossing', I have the same for other apps

![free_cam](https://user-images.githubusercontent.com/11719573/44882360-4285f980-acb3-11e8-9a50-d832fd07f6ec.png)

**Comment by MichaelPFrey** [comment]
> This allow to make specific stuff at first preview :
> *Define a given camera position

I try to shape the idea a bit, so I describe an alternate approach: We could also use a "$vprDefault $vptDefault $vpdDefault"  variable that is applied until the user changes the camera. This "$vprDefault $vptDefault $vpdDefault" could also get its own button in the UI and its own button combination (CTRL+* for e.g.) so that the user can access this default at any latter point in time.

> *Some demo

A demo as in a specific set of parameters?
Or a demo as in an animation that is applying various presets one after the other?

> I think the simplest solution is to identify the first preview as specific with a system variable, only true during the first preview.
For testing, (and for the end user) I think you also need a way to go back in this demo state. For e.g. in the menu under view and linked to a button combination. So, it is not as simple as beeing true on the first preview and false on all others.

Seeing that you have the customizer open:
Would it be an alternative to have $customizer variable? $customizer beeing false, when it is a normal preview. $customizer beeing true when the preview is caused by the customizer (and/or variables are beeing overwritten by the customizer).
As the first preview is presumably not caused by the customizer, that should/could also work for your use case.

An other approach seeing that the customizer is open: You could simply use a preset that you ship with your design. "no preset" beeing demo mode.

**Comment by PRouzeau** [comment]
@MichaelPFrey 
Having default camera variables was my immediate idea, as the natural answer to my problem.
Though, I later thought to the idea that knowing the 'status' of the preview, while requiring a bit more complex implementation for OpenSCAD programmer, will open more possibilities.
As demo, yes, I was thinking to animation, but that need more features to autostart animation and in my view that shall be a different issue (a nice one, for sure). 
At least having one static image is simple. While having different values than the default, default being a base for the user to start with, demo being a show of what can be done.

@t-paul 
Indeed, that is the key point, having the original OpenScad interface to disappear to create a simulation mode only. Why will simulation not be the normal use of customizer? Was'nt that the intent of Thingiverse when they implemented this feature. Is'nt the main purpose to offer a user a nice and unique interface?
I think that open a lot of possibilities.
I indeed use some variables as control buttons, as the 'top view' one, but the user have to unclick after to free the camera, so that is not super practical.

I started to make simulations before customizer implementation, but Customizer made them much more functional. In fact my very first published OpenScad program was a simulation (The delta printer simulator).

I try to fit in the existing language structure and to minimize disruption. Yet special variables are the only way to control.

**Comment by MichaelPFrey** [comment]
just for future reference: about camera position see also #2385

**Comment by PRouzeau** [comment]
I did now detect the fact that we are in first preview by looking the default rotation vector: [55,0,25], which have extremely low possibility to be seen again because I did modify it immediately. If not the default, we let the camera at its existing position.
I did not looked the translation default vector [0,0,0] as it can be seen again.
The variable created can also be used for something else than camera movement.
That does look like that:

    //Impose camera position if rotation vector is default - to detect first startup
    Cimp = Enforce_camera_position||$vpr==[55,0,25]; 
    //Camera distance
    $vpd=Cimp?7200:$vpd; 
    //Camera translation 
    $vpt=Cimp?[400,0,900]:$vpt; 
    //Camera rotation
    $vpr=Cimp?[76,0,30]:$vpr; 

A (slightly) more complex sequence may allow to later switch on/off another camera position in customizer

    iview_type=false;
Then

     $vpd=Cimp?iview_type?8200:7200:$vpd; 
etc.

or multiple views in addition to the first preview

     iview_type=0; // [0:not imposed, 1:view 1, 2: view2]
Then

     $vpd=Cimp?iview_type==2?8200:(iview_type==1?5000:$vpd):3000; 
etc.

**Comment by t-paul** [comment]
A language extension for this special case will cause too many issues. There's already a DBus interface which allows controlling the viewport (of dev snapshots / Linux only) externally. That might be the base for a feature like that.
