### ISSUE TITLE
Dark mode on Mac, text is not visible.

### ISSUE THREAD

**Issue by LazaroFilm** [openscad/openscad#2785]
On the last lightly build version 2019.01.30 
When my mac is in dark mode the text disappears as it's white text on white background. I can reveal it by highlighting it. See screenshot, in the console and the About, I highlighted part of the text. You also see the customizer fields appearing blank but they actually have values in them. 
<img width="1920" alt="screen shot 2019-02-12 at 11 21 27 am" src="https://user-images.githubusercontent.com/18351100/52650612-9595e680-2eb8-11e9-803e-615a5110a2b4.png">

**Comment by t-paul** [comment]
See also https://bugreports.qt.io/browse/QTBUG-68850

**Comment by DAKarp** [comment]
Agreed this is broken. Until it's fixed, the following works: https://www.tekrevue.com/tip/exclude-app-dark-mode-macos-mojave/

**Comment by pokono** [comment]
+1

**Comment by robske110** [comment]
Also the preferences window has black text on a dark background. (And the toolbars have a weird contrast too)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16020100/58760974-0aac2b00-853f-11e9-9723-240b01757472.png">

**Comment by jottr** [comment]
You can disable dark mode for OpenSCAD by issuing the following in your Terminal:


 ```
$ defaults write -app OpenSCAD NSRequiresAquaSystemAppearance -bool true
```

**Comment by LazaroFilm** [comment]
> You can disable dark mode for OpenSCAD by issuing the following in your Terminal:
> 
> ```
> $ defaults write -app OpenSCAD NSRequiresAquaSystemAppearance -bool true
> ```

That's more like a cop out than a bug fix. If I use dark mode, it's to limit eye strain at night. I don't really want to be assaulted by a bright white window.

**Comment by t-paul** [comment]
There is currently no developer on MacOS and Apple does not allow development on non-Apple hardware. So fixing this issue may take some time.

**Comment by TheJKM** [comment]
Looks like a QT bug to me, probably because the used version is outdated. If I compile the latest Git on my machine (macOS 11.1), it looks much better. I'm using the latest QT, version 5.15.2. This is working for quite some time now, I'm using self built versions for almost a year now because of this problem.
I remember other applications having similar problems when using older QT versions.

<img width="1680" alt="Screenshot 2020-12-25 at 20 20 28" src="https://user-images.githubusercontent.com/21987613/103141038-f6b2b600-46ee-11eb-9570-24a4d05bb67c.png">

(Off topic: there was a bug causing QScintilla not to work properly, which resulted in no syntax highlighting. Seems to be resolved, as QScintilla is working in the build I made today.)

**Comment by yorb** [comment]
Just updated to 2021.01 and noticed dark mode is no longer an option. While it does improve legibility, it obviously isn't an ideal solution. :) So I guess I'm just adding my vote for this to get resolved at some point.

**Comment by amandamana** [comment]
Please add dark mode support

**Comment by t-paul** [comment]
Closing this one, #3775 shows it's a Qt5 issue so tracking continues there.
