### ISSUE TITLE
Customizer range bug

### ISSUE THREAD

**Issue by nyponen** [openscad/openscad#2931]
In the following code snippet, the customizer limits the first variable incorrectly to a maximum of 1.3. The second variable works correctly. OpenSCAD version 2019.01-RC4 

incorrect_range = 1.0;    // [0.5:0.1:1.4]
correct_range = 1.0;    // [0.5:0.1:1.5]

**Comment by nophead** [comment]
I think it is because 1.4 is a recurring binary fraction, so will always be slightly less than 1.4, whereas 1.5 can be represented exactly. Also 0.1 is a recurring fraction in binary, so all the values will be a bit off.

This bodge works.
```
incorrect_range = 1.0; // [0.5:0.1:1.40001]
```

For loops with those ranges are even more broken.
```
for(i = [0.5:0.1:1.4]) echo(i);
    
for(i = [0.5:0.1:1.5]) echo(i);
ECHO: 0.5
ECHO: 0.6
ECHO: 0.7
ECHO: 0.8
ECHO: 0.9
ECHO: 1
ECHO: 1.1
ECHO: 1.2
ECHO: 1.3

ECHO: 0.5
ECHO: 0.6
ECHO: 0.7
ECHO: 0.8
ECHO: 0.9
ECHO: 1
ECHO: 1.1
ECHO: 1.2
ECHO: 1.3
ECHO: 1.4
```

If you want precise steps don't use floating point ranges. Use integer ranges and divide by 10 in this case.
