### ISSUE TITLE
if statements do not seem to work as expected

### ISSUE THREAD

**Issue by billy1380** [openscad/openscad#3067]
I am getting some odd behaviour that I cannot explain:
This code sample works well... and you can see 14 printed in the console
```
a = 12;
b = 12;

c = (b==12 ? 14 : 0);

echo (c);
```
but when I change c to a, things start to become unexpected
```
a = 12;
b = 12;

a = (b==12 ? 14 : 0);

echo (a);
```
There are now warnings in the console
```
WARNING: a was assigned on line 1 but was overwritten on line 4
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown variable 'b', in file ./, line 4.
```
and the echo-ed value is 0

**Comment by nophead** [comment]
If you assign ```a``` twice it moves the second definition to the first one and uses that value throughout. I.e. a variable can only have one value. In your case it moves the statement that uses ```b``` before the definition of ```b```, hence the confusing error message.

Simply remove the first assignment to ```a``` and it will work.

**Comment by billy1380** [comment]
is there anyway to treat `a` as variable or define something with the intent of changing it?

**Comment by nophead** [comment]
No OpenSCAD variables are actually more like constants in other languages. Rather than thinking of it as a executing program it is more like a static description of geometry. In a description of a solid nothing needs to change during that description. If you want another value you have to give it a new name.

The only exception is ```$t``` changes to allow animations but each frame is a separate execution of the script, so it only has one value everywhere for each frame.

You can override a default value. For example a library could define a variable ```a = 3``` and after including it you can do ```a = 2``` but a will be 2 everywhere.

**Comment by billy1380** [comment]
Thanks again @nophead, that makes sense.
