### ISSUE TITLE
CGAL error in Polyhedron3...

### ISSUE THREAD

**Issue by Fuechsl** [openscad/openscad#3100]
Hi developers,

I encounter a strange error/behavior in OpenScad 2019.5 Mac today:
<img width="1101" alt="Bildschirmfoto 2019-10-22 um 19 52 25" src="https://user-images.githubusercontent.com/56889899/67315362-b3ffb780-f506-11e9-9ec7-9bf2897d1fc9.png">
I reduced my construction as far as possible to reproduce the error. Those are the files needed:
[ErrorOpenScad.zip](https://github.com/openscad/openscad/files/3757590/ErrorOpenScad.zip)
plot_function.scad is a library I found on thingiverse.

If you try to generate CGAL in the ErrorOpenScad you get the error from above.
You can avoid it either by setting the var wellenquali in line 8 to a value bigger than 1 (so 1.01 i.e.) or delete line 19.

I don't know if I'm doing something wrong, the library has a problem or OpenScad itself, but it seems the latter to me.

Regards, Martin

**Comment by MichaelAtOz** [comment]
Your problem is the shared face of the two objects.



 

It is non-manifold to share the same face of two objects.

It breaks the "all edges must be shared by exactly two polygons (usually triangles)" rule.

It can't tell weather something is 'inside' or 'outside' the object.

Which is why moving it a little fixes the error.

When dealing with multiple objects, it is best practice to either have them clearly separate or
embedded into a face, not just touching.

 

 

 

  _____

**Comment by MichaelAtOz** [comment]
There was an image in that gap above, don't know where it went..., this one:
![face touching](https://user-images.githubusercontent.com/1972961/67359039-f4fed700-f5ad-11e9-82ff-7b8b6dac56df.png)
