### ISSUE TITLE
Some thing evil in rotate_extrude?

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3168]
From #3117, various code producing self-intersections and duplicated triangles.
With 2019.05 & 2019.11.20.
```
difference (){
  translate ([5,-2,0])
    cube ([20,4,4]);
  translate ([0,0,2])
    rotate_extrude(angle=360,$fn=60)
      translate ([11,0,0])
        circle (d=3.4);
}
```

Exported, Netfabb shows; (SI's at top of circle)
![Capture#3117-2](https://user-images.githubusercontent.com/1972961/71383999-f478d000-2632-11ea-9cb1-d95ea74dae14.JPG)

Close-up;
![Capture#3117-2 closeup](https://user-images.githubusercontent.com/1972961/71384038-330e8a80-2633-11ea-9128-67b37980cfae.JPG)
The white triangles according to Netfabb are 'duplicate triangles', the yellow marks are where an  vertex is in the middle of an edge, hence degenerate triangles. [note the Netfabb default colour setting is not white but orange, I changed it to make sure I knew what type it was]

STL [#3117-2.zip](https://github.com/openscad/openscad/files/3996537/3117-2.zip)

Unlike @bakerjvp I have yet to get a crash.

**Comment by nophead** [comment]
I suspect it is because one of the segment junctions of the torus meets the top of the cube at a slight angle and the  difference creates the normal vertices too close for the grid problem.

A tricky thing to avoid but I think if the segments junctions are wholely inside or outside the cube it would work.

**Comment by MichaelAtOz** [comment]
Yes it is at the tapered segment of the torus;
![Capture#3117-3](https://user-images.githubusercontent.com/1972961/71385882-28a5be00-263e-11ea-88fc-f57b814d4f5d.JPG)

So yet another grid/small-float issue. 
This is bad, that it a perfectly normal bit of code, which should not need workarounds.

**Comment by MichaelAtOz** [comment]
Indeed, `rotate(2)` the `rotate_extrude()` moves the segment edge and produces a good STL.
![Capture#3117-3-rot](https://user-images.githubusercontent.com/1972961/71386051-3c9def80-263f-11ea-8a4b-8728fddab3fd.JPG)

These issues give OpenSCAD a bad reputation...

**Comment by MichaelAtOz** [comment]
Closing, track via #2686 or #2991.

**Comment by thehans** [comment]
> These issues give OpenSCAD a bad reputation...

Is this STL showing errors in any program besides Netfabb?  Maybe the issue is with netfabb doing some processing upon import and messing up things which were fine.

I checked that re-importing to OpenSCAD and doing CGAL ops on the STL works fine, no non manifold warnings or anything.  

Also using Meshlab and choosing "Filters -> Selection -> Select Self Intersecting Faces" doesn't pick up anything...

Unless there's any second program to corroborate Netfabb's findings, I'm inclined to blame Netfabb.

**Comment by MichaelAtOz** [comment]
Hmmm.
Here is one I prepared earlier
![Capture strut](https://user-images.githubusercontent.com/1972961/71388419-67427500-264c-11ea-81a8-27f2ff456380.JPG)
```
// to sharpen the pillar
!difference() {
  import("pillar.stl");  
  import("sharpner.stl");
}
```
STLs produced by OpenSCAD appear clean, [pillar.zip](https://github.com/openscad/openscad/files/3996909/pillar.zip)

Via
```
//to create a pillar: pillar 1
linear_extrude (height=80)
  union() {
    translate ([0,-1.1,0])
      color ("blue")
        circle ($fn=40,d=4);
    translate ([0,1.1,0])
      color ("blue")
        circle ($fn=40,d=4);
    translate ([-2,-1.1,0])
      resize ([4,2.2,0])
        square (4);
  }
```

```
//to create sharpner 1
difference () {
  translate([-7,-7,60]) 
    cube ([13,13,20]);
    $fn=60;
  translate ([0,0,60])
    cylinder (r1=3.5,r2=0.1, h=25);
}
```
