### ISSUE TITLE
incorrect rendering

### ISSUE THREAD

**Issue by vuvova** [openscad/openscad#3472]
This works:
```
LL=100;
W=38;
module nut() {
  module twosides() { square([LL,W], center=true); }
  intersection() {
    twosides();
    rotate([0,0, 60]) twosides();
    rotate([0,0,120]) twosides();
  }
}
linear_extrude(4)
difference() {
  circle(d=60);
  nut();
  translate([0, LL/2+W/2-0.0001]) square([LL,LL], center=true);
}
```
but if you remove `-0.0001` the object is rendered incorrectly, solid, without a hole

**Comment by t-paul** [comment]
This is a caching issue, I'm almost sure we have an issue for that somewhere. It works with just F6 (or Design->Flush Caches + F6).

**Comment by vuvova** [comment]
It doesn't seem to work with just F6 (just = directly after opening the file) or with Design->Flush Caches. At least not with the version 2019.05.

**Comment by Scopeuk** [comment]
This appears to come in during the linear extrude.
preview appears to show the shape is correctly derived in two dimensions however running a render results in a solid shape, a circle with a missing edge) which matches the extruded shape, possibly due to the 0 width edge closing the shape(someone with more knowledge of the pipeline may be able to help here).
substituting the -0.0001 for a +0.001 also produces a valid shape unfilled which then exports.
-0.0001 (2D)
![image](https://user-images.githubusercontent.com/44125258/99150762-b8a58980-268e-11eb-8ca0-c1dab516b808.png)
0 (2D)
![image](https://user-images.githubusercontent.com/44125258/99150770-cbb85980-268e-11eb-8cbd-358ef3a846fd.png)
+0.001
![image](https://user-images.githubusercontent.com/44125258/99150778-da9f0c00-268e-11eb-8b99-04b2fcd78f66.png)

**Comment by kintel** [comment]
Status as of 2024-03-24: Works now!
