### ISSUE TITLE
WARNING Message re Viewall, appropriate in GUI?

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3548]
With code playing with $vpr I get this message;
```
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
ECHO:$vpt = [0, 0, 0], $vpr = [55, 0, 25]
WARNING: Viewall and autocenter disabled in favor of $vp* location unknown 
Rendering Polygon Mesh using CGAL...
```
Only with view/view-all previously selected.
I can see it being relevant with command line use to highlight conflict with command line options,
but I think it is unnecessary in the GUI.

Suppress it in the GUI??

**Comment by nophead** [comment]
Yes it seems totally wrong to me. The only way I can use $vp* variables is to disable stop on first warning. Otherwise the preview is aborted. Also viewall and autocenter are not disabled, they still work. F5 resets the view to match the $vp* variables but then you can change it with the mouse and the tool bar buttons.
