### ISSUE TITLE
Joystick won't bind anything to Relative Y

### ISSUE THREAD

**Issue by jmorris70634** [openscad/openscad#3858]
Fedora + basic Logitech gamepad.  Everything else will bind just fine except that one.  Of course that is "walk forward" so the lack of it can't really be worked around.  Tried binding several axis to it, no luck.  All other combinations of controller axis and motion I tried worked perfectly.

The package is the Rawhide srpm built locally so I could get the 2021.01 release and have the best odds of things working.  And it does work otherwise.  Fairly complex model that takes 14:37 to fully render is perfectly happy.  Navigating a complex object by keyboard is well.... challenging.

Oh, and for the record.  2021.01 rocks.  The customizer is awesome.

**Comment by MichaelPFrey** [comment]
> Joystick won't bind anything to Relative Y 

you are in orthogonal view. Relative Y only works in Perspective view.

![perspective](https://user-images.githubusercontent.com/24962768/157748259-d50169fb-0148-496d-84d6-0567b86507ae.png)

> Of course that is "walk forward" so the lack of it can't really be worked around. 

Incorrect, that is what Zoom is for:

![zoom](https://user-images.githubusercontent.com/24962768/157748514-6e1bde9a-2627-4bef-9de7-9cc87a588aa9.png)

There are two mappings for Zoom, so that one analog trigger can be used for zooming in and one can be used for zooming out.

If you wonder why you have access to relative Y, when it is not intuitive to use: The input driver gives you full control of the camera. Modifying both zoom and relative Y changes the angle of view.

see also
- https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Input_Devices#Y+Viewport-rel-translation_(VRT)_Channel_is_not_responding_to_input
- https://en.wikipedia.org/wiki/Angle_of_view
- https://en.wikipedia.org/wiki/Angle_of_view#/media/File:Camera_focal_length_distance_house_animation.gif
-  https://en.wikipedia.org/w/index.php?title=Vertigo_effect

I will also update the wikibooks to clarify that.
