### ISSUE TITLE
variables inside for loop do not get updated to next loop

### ISSUE THREAD

**Issue by JelbertHoltrop** [openscad/openscad#3914]
My computer macbook pro 16" 2019 OS Big Sur 11.6
this code:

`/*
The values between loops are not stored. How do I get the code below to work?
version used 2021.01
*/

a=0;
b=0;
c=0;
d=0;

for(i=[1: 1: 5])
{
    x=cos(i);   //get some calculated value
    y=sin(i);
    dx=x-a;     //use the value from te previous loop
    dy=y-b;
    a=x;        //store the value for the next loop
    b=y;
    c=sqrt(dx^2+dy^2); //get the distance between the two points of two loops
    d=d+c;             // store the total distance 
    echo(d,c,x-dx,y-dy);
    //d should increase every loop
    //c is the distance between this point and the previous point.
    //if c is 1 values a and b have not survived from previous loop
    //x-dx should not be 0
    //y-dy should not be 0
}
echo(d);`

results in:
ECHO: 1, 1, 0, 0
ECHO: 1, 1, 0, 0
ECHO: 1, 1, 0, 0
ECHO: 1, 1, 0, 0
ECHO: 1, 1, 0, 0
ECHO: 0

In any other language this should work

**Comment by t-paul** [comment]
This behavior is normal, and is similar to other description languages. See also [FAQ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_am_I_getting_an_error_when_writing_a_=_a_+_1?).

See https://en.m.wikibooks.org/wiki/OpenSCAD_User_Manual/List_Comprehensions for ways to generate arrays. Otherwise please post general questions on the mailing list or one of the other [discussion places](https://openscad.org/community.html).
