### ISSUE TITLE
Improve GUI responsiveness for complex objects in preview mode

### ISSUE THREAD

**Issue by maudette01432** [openscad/openscad#418]
The code seems to render properly but afterwards I am unable to rotate the object in the display window.  Editing also becomes very unresponsive as well as file IO operations.

Openscad version 2013.06 (OSX)

```
$fn=80;

module oval_flat(diameter) {
  union() {
    hull () {
      circle(r = diameter/2, $fn = 100);
      translate([0,5,0]) circle(r = diameter/2, $fn = 100);
    }
  }
}

module cross_section(diameter, thickness) {
  difference() {
    oval_flat(diameter);
  }
}

module pie_slice(radius, angle, step) {
  for(theta = [0:step:angle-step]) {
    rotate([0,0,0])
    linear_extrude(height = radius_2, center=true)
    polygon(points = [
      [0,0],
      [radius * cos(theta+step), radius * sin(theta+step)],
      [radius * cos(theta), radius * sin(theta)]
    ]);
  }
}

module partial_rotate_extrude(angle, radius, convex) {
  intersection () {
    rotate_extrude(convexity=convex, angle=angle) translate([radius,0,0]) children(0);
    pie_slice(radius*2, angle, 1);
  }
}

union () {
  partial_rotate_extrude(180, 16, 10) cross_section(4,2);
  translate([4,0,0]) rotate([0,0,180]) partial_rotate_extrude(270, 20, 10) cross_section(4,2);
}
```

##

**Comment by curiouspl2** [comment]
+1 on this one.
IMHO UI should be responsive as design priority , otherwise it breaks flow. 
So well - moving to separate thread is quite main thing i thnk, 
and then methods to actually being able to somehow handle big objects : 
1)bounding box instead of full updates when doing any viewport translate by mouse - this way one can 
actually rotate etc. just bounding box. then once happy with new position - release mouse button. 
preview should just silently catch up, but in case user changes mind and tries to rotate bit more - once again bounding box should be all the time on top priority instead of locked by rendering loop.

2)incomplete/bailed out previews or using data from 'render' (f6) as gfx while rotating. 
There are many methods to get somewhat crippled but still manageable objects for just rotating by UI. 
one can just view wireframe renderition, some simplified shapes (with simplification limits set by preferences) etc. etc. while rotating. 

3)only marked (in the source code) objects show up in preview while rotating. not sure how to get the marking, just special color objects visible while rotating perhaps?

**Comment by jorisrobijn** [comment]
Hi, same here, for a complex design. It appears however, that this starts occurring after some threshold is crossed. If I remove a couple of (identical) complex objects, F5 results in a slowly updated object but works. Adding them again one by one and suddenly it's problematic. It keeps doing something and doesn't finish. Often requires killing the process to get out. And also for me, after an F6, rotating and moving the object in the GUI is incredibly fluent. But F6 takes a couple of minutes to compute.

**Comment by nophead** [comment]
You probably need a carefully placed call to render() to improve the preview responsiveness. I think 3D intersection is particularly slow.

I code as much as possible in 2D and use extrude and rotate_extrude to make 3D objects, avoiding 3D difference and intersection as much as possible. If I do use them I use render() to keep the preview responsive and prevent negative objects Z-fighting.

**Comment by thehans** [comment]
Closing this very old issue as many improvements have been made since it was opened.

The original script is very inefficient, and gets about 1 frame per 5s on latest release.  The quickest fix is to simply move the `linear_extrude` of `pie_slice` outside of the loop.  This makes it much more efficient because the polygons then get unioned in 2D, instead of 3D.  Preview becomes effectively instantaneous.

```
module pie_slice(radius, angle, step) {
  linear_extrude(height = radius*2, center=true)
  for(theta = [0:step:angle-step]) {
    rotate([0,0,0])
    polygon(points = [
      [0,0],
      [radius * cos(theta+step), radius * sin(theta+step)],
      [radius * cos(theta), radius * sin(theta)]
    ]);
  }
}
```

Also note that `rotate_extrude` has had `angle` parameter added since this issue was opened, which completely removes the need for `pie_slice` in the first place.

Lastly I figured I might as well mention that the VBO renderer Experimental Feature (available in the nightly builds) also helps quite a bit even with the unmodified original example, becoming something like 3-4 fps screen refreshes for me.
