### ISSUE TITLE
Collapsed console area

### ISSUE THREAD

**Issue by nfedyashev** [openscad/openscad#4289]
![openscad-collapsed-console](https://user-images.githubusercontent.com/61983/175772056-a5b31c91-6380-43c2-9355-356e83c61261.png)

Linux(debian), i3
I'm not sure what changed because it worked fine last time I used it(same version).
I can't find a way to enlarge it after it collapsed.

The only workaround to find out what's in the console is right-click, select-all, copy and paste it elsewhere.

**Comment by thehans** [comment]
You should be able to click and drag the "border" between the 3D view and Console.  There is a barely visible indicator of this draggable area.  

![175772056-a5b31c91-6380-43c2-9355-356e83c61261](https://user-images.githubusercontent.com/252233/175789291-dddf989b-a1c4-40cf-bb84-549db4fffe35.png)

Although the dotted line is narrow and centered in this case, clicking anywhere along this horizontal should work.

Unfortunately, I think the visibility of this is dependent on your OS and desktop theme settings rather than something controlled directly by OpenSCAD.

**Comment by nfedyashev** [comment]
@thehans thank you!
