### ISSUE TITLE
Q: How to convert a Fusion 360 / Solidworks file to Openscad

### ISSUE THREAD

**Issue by philipphirte** [openscad/openscad#4553]
Hello!
I want to convert Fusion 360 and Solidworks files including the parameters into openscad files or import them, but with parameters?
How would one do this?

**Comment by t-paul** [comment]
The only possible path I can see is trying to open the file in FreeCAD (via STEP format) and exporting as OpenSCAD. I've never tried that so it might not work at all or produce unusable results.

Otherwise, this would be more a question for the mailing list - https://openscad.org/community.html#forum
