### ISSUE TITLE
How to access "export_stl" from within my OpenSCAD script?

### ISSUE THREAD

**Issue by w1ebr** [openscad/openscad#4829]
In looking at the source files, there are several options for importing and exporting files in different formats. What is the OpenSCAD command to export the model as a STL file?

**Comment by jordanbrown0** [comment]
You can't.  The language has some facilities for importing files, but no ability to write files.  (This is deliberate, so that a malicious OpenSCAD program can't scribble on your disk.)

What you need to do is either:
* From the application, F6 render (or Design/Render) then F7 export (or File/Export/Export as STL...)
* From the command line, `openscad -o <name>.stl <name>scad`.

**Comment by jordanbrown0** [comment]
By the way, the mailing list is generally a better place to ask questions.
https://lists.openscad.org/list/discuss.lists.openscad.org

**Comment by w1ebr** [comment]
I am processing a lot of files (34 right now). Each input STL is "import"ed. Is there a way to pass this information via command line?

**Comment by w1ebr** [comment]
Also, is "manifold" an option I can try? If so, how do I do this?
Thanks!

**Comment by jordanbrown0** [comment]
Better than trying to do Q&A here would be to switch to the IRC channel.  If you have an IRC client, #openscad on irc.libera.chat.  There's also a web interface at https://web.libera.chat/?channel=#openscad

**Comment by jordanbrown0** [comment]
Questions answered in IRC, issue can be closed.
