### ISSUE TITLE
STL export of an object with an internal cavity has the internal faces the wrong way round [$150 awarded]

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#495]
Summary:
- Objects with cavities are exported with the cavity polygons facing the wrong way. This is probably a CGAL bug. See proposed fix from CGAL below
- Objects with cavities (with correct winding) are not converted correctly to Nef polyhedrons and won't behave correctly in CSG operations. This goes both for imported objects and for polyhedron()-defined objects.

To close this issue, both these things should be fixed.

This is with OpenScad 2013.06.

```
module hollow_cube()
    difference() {
        cube(20, center = true);
        cube(10, center = true);
    }

// set X to 0 and export cube.stl
// set X to 1 to see what it should be
// set X to 2 and see it is broken

x = 0;

if(x == 0)
    hollow_cube();

if(x == 1)
    difference() {
        hollow_cube();
        translate([-20, 0, -20]) cube(100);
    }

if(x == 2) 
    difference() {
        import("cube.stl", convexity = 5);
        translate([-20, 0, -20]) cube(100);
    }
```

When the object is exported to an STL and then imported again to take a cross section it looks like this.

![cube](https://f.cloud.github.com/assets/566149/1232951/0f4b39a2-28f8-11e3-9fd5-99cf2e51e658.png)

The exported object is also wrong when cross sectioned in NetFabb stdio.
##

**Comment by hzeller** [comment]
The `CGAL_workaround_Mark_bounded_volumes.h` added in https://github.com/openscad/openscad/commit/e8bdf04d48673beeea15f116bbd6acc1c913738e adds the same symbols 
(`CGAL::Volume_setter`, `CGAL::Mark_bounded_volumes`) in the same namespace as the system-`<CGAL/Nef_3/Mark_bounded_volumes.h>` which requires some delicate [dance to make sure it is seen first](https://github.com/openscad/openscad/blob/master/src/geometry/cgal/cgal.h#L17), which makes it very brittle and makes assumptions of how the system headers include each other (I noticed in the context of cleaning up headers).

I wonder

   * Could the symbols be renamed or put in a different namespace so that this is not a problem ?
   * or: maybe this work-around is not needed anymore in current CGAL ? (maybe CGAL got fixed in the last 10 years since this was fixed here ?)
