### ISSUE TITLE
glib2 is a giant library, only used for utf8, and should be dropped

### ISSUE THREAD

**Issue by brianolson** [openscad/openscad#594]
glib2 is about half a million lines of source, and openscad is only using maybe 2000 lines of it for some utf8 library code. openscad should drop glib2 for a smaller library (probably one that just deals with unicode).

**Comment by donbright** [comment]
can we close this now? it would be nice to have less dependencies, but i just built openscad on 7 different linux machines without much problem. The build scripts for linux have been updated to deal with all these new libraries. Unicode text rendering is part of internationalization and appears to be baked into the core of modern linux distributions. It has also found it's way into MSYS and MSYS2 and the MXE cross-builder (for Windows(TM)). BSD surely ain't too far behind. 

I noticed this issue is prompted by problems building on OSX. I also noticed in the makefiles that OSX seems to have lots of build problems over the different releases of XCode and OSX, but IMHO those should be "OSX build fail" issues not generalized build issues. If someone wants to donate me a Mac i can set up different OSX versions in a VM and fix OSX build problems :)

**Comment by donbright** [comment]
interesting note for historical researchers: 

Microsoft is now giving free downloads to Windows 10 insider preview, including installing it in a VM, and keeping it for free after release date. 

Apple makes it illegal to run OSX on non-apple Hardware, and also makes it illegal to run OSX inside a VM unless it is on Apple hardware. This has also made it harder to build OSX cross compilers to run from within linux. (see the https://github.com/tpoechtrager/osxcross project on github).

**Comment by t-paul** [comment]
Right, I'm closing this now. If there are specific build problems, we can open a new issue.

**Comment by MichaelAtOz** [comment]
> Apple makes it illegal to run OSX on non-apple Hardware

Do they test for that?

**Comment by donbright** [comment]
it's not relevant whether they test for it. if you are an open source developer you have to follow the IP law to the best of your ability because you are risking not just your own self but the other people working on the project, the project itself, the users, and the project's future.  

you cant ship a product with the instructions "hey.. ok.. to install our product, first step, break the law and dont get caught"

a good bad example is what happened to the ReactOS project

https://en.wikipedia.org/wiki/ReactOS#Internal_audit

there are many others.

**Comment by MichaelAtOz** [comment]
I wasn't suggesting that, I was just curious.

**Comment by donbright** [comment]
well there are a plethora of X86 Hackintosh websites out there so ... so Apple doesn't appear to be testing this at the present time in a rigorous fashion (for example i have read you can install the App Store and do OS system updates and upgrades on a hackintosh). 

But Apple could decide to change their de-facto policy at any moment and start implementing a rigorous testing program and begin banning "non Apple" users from things like updates, account access, app store access, etc.... sort of like back around 2000 when Microsoft went from turning a blind eye to Windows pirated versions, to creating the 'Activation Key' system where a sticker comes on every machine with a 20 digit code tied to the machine configuration, and requiring you to "Activate Windows" before you can log on or do system updates. Apple could do something like that any time they wanted, leaving Hackintosh owners in a problematic situation. Non-Apple VM OSX could be in the same boat as the Hackintosh owners.
