### ISSUE TITLE
Customizer-like GUI [$150]

### ISSUE THREAD

**Issue by o-jasper** [openscad/openscad#722]
I really like the idea of the customizer, but dont want to depend on thingiverse for it. It allows designers to put the parameteric capability of openscad at the end user. (This is another case of 'how is it that i cant find an existing issue', by the way.. I half expect i put this issue here before and i forgot?)

The idea of a customizer is of course that you enter parameters, files and the openscad is run using those particulars. I would suggest a separate mode/program that doesnt just all the design-development stuff of openscad.

The simplest approach is to have a separate form you can fill in with with numbers/text/sliding bars/drop boxes etcetera and the model as with current parameters beneath it.  A `.scad` file would specify description texts and how different parameters can be specified. 

The 3d model shouldnt disappear while updating i reckon. (though it should be clear whether it is currently up to date with the parameters.)

A more complicated way to do it is to have kind-of thingies around the 3d model itself, that you can drag and stuff. Expect that this is nice, and has a 'good look', but dont at all think it is necessary.
##

**Comment by t-paul** [comment]
As @m4444x has deleted everything and did choose to not answer any questions regarding the license, I was forced to throw away all the stuff based on that and start from scratch :angry:.

Anyway, the current state is in the [parameter-gui](https://github.com/openscad/openscad/tree/parameter-gui) branch now. (https://www.flickr.com/photos/96851846@N05/16000210899/)

For the record: I'm not going to claim any part of the bounty. Should there be no other claim in the end, it will be redistributed to other issues.

**Comment by TimtomToorsten** [comment]
dingdongdang - Please derail these threads immediately. A licensed highspeed troll train is passing - toootooot chochochocho

**Comment by MichaelAtOz** [comment]
We need to define whether;
a. It is a non-OpenSCAD lanuage feature like #define pre-processor in C, thus IMO a kludge, or
b. A feature of the OpenSCAD language, built-in facility, integrated and able to develop in the future.

Two very different approaches. Two different camps.

In my view, a. is the past, and b. is the future. But hay, I'll just use whatever happens and bitch about it.

and

c. Needs to fix the command line -D interim solution. In this case I beleive it needs to support the current thing (set a variable), but go in a better integrated direction.

**Comment by kintel** [comment]
I don't think this type of backwards compatibility is very important. We should be able to assume that people can and will use the latest version of OpenSCAD.

The only place this is a problem is things like MakerBot Customizer, but we don't have any influence or responsibility for their development pace. If they cannot keep up, people will likely just stop using it, and competitors will pop up.

**Comment by laird** [comment]
My recollection is that Tony (Mr. Customizer) has already said, back when
this discussion started, that if OpenSCAD added a built in way to express
this, he'd intend to support it.

The concern that I have with doing this outside the language, using
something like comment parsing, is that it limits parameters to being
static. That covers many cases, and it's easy to implement, so it has some
value obviously.

But the more I think about it, the more I need parameters to be dynamic,
which means that a programming language (or markup with logic of some sort)
has to be in the picture. There are many use cases where there are
interactions or dependencies between parameters in a GUI. That is,
depending on one parameter value, other parameters may be hidden or shown,
or have different valid ranges or default values.

For a rough example, look at the Python 'argparse' library, which (for
example) Tim used in his example above, which lets python code define a set
of command line arguments (with types, help doc's, allowed values, input
validation, a nice explanation of the options of you run with -help, etc. -
it's very nice and easy to use). But instead of being used in Python around
OpenSCAD, for a command line, my suggestion is that a similar mechanism be
provided within OpenSCAD, as a method used by the GUI to define the
parameters that it wants to expose. The GUI would then collect user input
and evaluate the OpenSCAD script. To be truly dynamic, the OpenSCAD
function that defined the parameters would need to be re-evaluated as the
inputs changed.

Perhaps something like this?

// Set default values, which could be overridden by command line args or
user input in GUI
shape="Box";
height=10;
width=25;
length=100;
radius = 10;

module parameters() {
   AddParameter(var="shape",label="Shape",prompt="Select desired shape",
values=["0:Box","1:Sphere"]);
   if (shape==0) {
      AddParameter(var="height",label="Height",prompt="Enter the desired
height in mm", type="number");
      AddParameter(var="width",label="Width",prompt="Enter the desired
width in mm", type="number");
      AddParameter(var="length",label="Length",prompt="Enter the desired
length in mm", type="number");
      }
   else {
      AddParameter(var="radius", label="Radius",prompt="Enter the radius in
mm", type="slider", min=1,max=150);
      }
   }

I'd also suggest that from a command line that the parameter structure be
exposed somehow. Perhaps something like running "openscad -P" which could
output a JSON or XML representation of the parameters? This would work with
the -D parameter passing, so the output parameter structure would reflect
whatever was passed in.

I had been thinking that if the parameter() module weren't defined that
it'd be nice to have OpenSCAD return the list of all "constant" variable
assignments, but as I think about it, that's "two ways to do the same
thing" is bad. It might be better to teach everyone to make a parameter
module if they want to expose formal parameters (for GUI, validation, etc.).

On Fri, Jan 9, 2015 at 10:33 AM, Marius Kintel <notifications@github.com>
wrote:

> I don't think this type of backwards compatibility is very important. We
> should be able to assume that people can and will use the latest version of
> OpenSCAD.
>
> The only place this is a problem is things like MakerBot Customizer, but
> we don't have any influence or responsibility for their development pace.
> If they cannot keep up, people will likely just stop using it, and
> competitors will pop up.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/openscad/openscad/issues/722#issuecomment-69349571>.
>



-- 
Laird Popkin  |  Executive Director, Architecture
KAPLAN TECHNOLOGY
Kaplan, Inc. | 6301 Kaplan University Avenue, Fort Lauderdale, FL 33309
tel +1 954 515 4509 | email laird.popkin@kaplan.com

**Comment by t-paul** [comment]
Example of how it can look like using meta data
http://files.openscad.org/video/screencast-parameter-window.webm

The same framework allows for other things by attaching meta data not only to global assignments but also to module definitions and their default assignments. The following example shows how adding meta data to library modules could make their usage easier by listing them and providing UI controls to modify parameters.
http://files.openscad.org/video/screencast-library-window.webm

Depending on the time of evaluation of the meta data (module definition ```module nut(r = 3) { ... }``` vs. module instantiation ```nut(r = 8);```) that same logic could also handle things like BOM collection or defining material properties or [modifier meshes](http://slic3r.org/blog/modifier-meshes).

**Comment by traverseda** [comment]
I'd like a way to save the parameters. Ideally to a seperate file container just the paramater overrides.

Maybe you could do something like "use <options.scad>" to set the default values to some new set of defaults. Make it so that the paramater generator just creates a new scad file which stores your defaults.

Sorry if you've already gone over that, just dropping in at the tail end of this.

Looks awesome!

**Comment by bobc** [comment]
Some technical notes: the wiki page is now https://github.com/openscad/openscad/wiki/Project:-Form-based-script-parameterization

The syntax:
```
  /**
  * This is a description of the function
  *
  * @param type $parameter1 Description
  * @param type $parameter2 Description
  * @return \SomeType Description
  */
```
is doxygen/JavaDoc type meta-comment, several editors support this. I think we would want to avoid our customizer syntax getting confused with that.

Some opinion: Personally I like to keep things simple, there seems to have been a bit of feature creep here! I don't like putting data into comments, comment syntax should be reserved for genuine comments. Equally putting meta stuff into the main syntax is a tricky path to follow for various reasons. OpenSCAD syntax is not evaluated like a procedural language, so customizer syntax is necessarily a "preprocessor" type function.

Obviously one reason for a customizer is a lack of variables and run time support for dialog boxes etc....but I don't think we want to implement that via the back door with a complicated spec. It would be better to implement a Python front-end IMO.

I had a look at @t-paul demo and the solution looked really nice and straightforward. It seems to meet the original requirements, is easy to use and fits well with the language, and is also extendable. It gets my vote!

**Comment by bobc** [comment]
@t-paul do you have a link for your parameter-gui branch? The link above does not work (not found). I would like to try adding properties for layers in a similar manner for customizer parameters.

**Comment by t-paul** [comment]
Updated for current master just now: https://github.com/openscad/openscad/tree/model-meta-data3

**Comment by Neon22** [comment]
link doesn't resolve ? goes to top level...

**Comment by t-paul** [comment]
Yes, top-level in the source tree, but it selects the `model-meta-data3` branch.

**Comment by Neon22** [comment]
@t-paul - looks really good :)
1. will it work if using OpenSCAD animation params ?
2. to maintain backward compat how about this style ?

// Use existing method (so compat with customizer) of simple variable declarations
shape="Box"; 
height=10; 
width=25;  //customizer comment in here but we ignore it.
length=100; 
radius = 10; 

// comments are of course optional and used by customer but ignored by new UI approach
// Then define the GUI as either a new function (requiring an update of OpenSCAD - undesirable)
// OR as a variable - which will be ignored by older versions as not used.
// In next versio of OpenSCAD could update by replacing varable with function. (Simple text Replace)
// E.g.

__UI = [ [shape,  label="Shape",  prompt="Select desired shape", values=["0:Box","1:Sphere"] ],
         [height, label="Height", prompt="Enter the desired height in mm", type="number", ifdef={(shape == 0)}],
		 [width,  label="Width",  prompt="Enter the desired width in mm",  type="number", ifdef={(shape == 0)}],
		 [length, label="Length", prompt="Enter the desired length in mm", type="number", ifdef={(shape == 0)}],
		 [radius, label="Radius", prompt="Enter the radius in mm", type="slider", min=1,max=150,
			ifdef={(shape == 1)}],
		 [volume, label="Volume of shape", value = {shape==0 ? width*length*height : 4/3pi*(pow(r,3))}]
		];
// The ifdef param defines any code used in a test to see if the value is made visible or not.
// Its also possible the UI wants to report to the user a value rather than allowing user input.
// E.g. wanting to inform them of the overall length of a model based on user entered part lengths (or reporting radians while asking for degrees. Above I have used example of indicating volume
// In this case use "value" param to be a calculation.

**Comment by t-paul** [comment]
@Neon22 interaction with animation is not actually tested yet. I guess both things can co-exist easily from a functional point of view. The actual implementation might have a number of challenges though.

Backward compatibility is not that much in focus as all this is basically new features. One of main reasons for introducing a new syntax is to attach the meta data directly at the places where it's intended to be without the need for referencing via a name.

There's at least 3 different places where the data can make sense for different use-cases
* _variables_: e.g. for model parameters similar to the original Customizer request
* _module definitions_: to annotate library entries for easier use and customization of parts; for things like BOM creation the definition would need to be carried over to the actual module instances to be evaluated later
* _module instantiations_: e.g. to attach layer information for DXF export or material meta data for AMF which could be directly used by other software like slic3r (maybe that would need to be restricted to top level data?)

Handling all 3 cases with additional variables would make things much more complicated, I think.

**Comment by ke7ofi** [comment]
I feel like most people who want to throw in numbers and have it pop out STLs aren't going to want to download a .scad file as well. If they're going to do that, they could just do what I do already: have a set of variables at the top of the file with a comment which says “These are the ones I can change.”. For that reason, it seems like some sort of web or command-line (for scripts) interface would be the most useful.

If you do want to keep it integrated, I did like @blue-ice's idea of having dedicated files. Do either of those ideas make sense?

**Comment by runsun** [comment]
Some idea along this script parameterization line of thinking: https://youtu.be/rNkvXI-PQsU

I'd call this "**Click-Change**" approach, that any number could be modified by clicking directly on it. The advantages over the proposed **form-based** parameterization (as demo'ed in [here](https://youtu.be/_oO4mTp2ieQ),  [here](http://files.openscad.org/video/screencast-parameter-window.webm) and [here](http://files.openscad.org/video/screencast-library-window.webm) ) are :

1) Don't need to type extra meta text 
2) Changable data doesn't have to be limited to those defined by the "a = value;" statement --- any number, even number in a list, [ [2,3,4] ...], can be changed on-site.

As a result, any old openscad file can immediately take advantage of its features.

**Comment by t-paul** [comment]
@runsun we already have a very similar feature, the only difference is that it's keyboard based. Any number can be changed using ALT + Cursor keys.
It's not yet fully documented in the manual, but I've already created a short screencast snippet to show how it works.

**Comment by ArktekniK** [comment]
@runsun I agree that those are benefits but you also lose the ability of the author to limit input on parameters to sane values.

For example, ranges for numbers, drop downs to switch between modes, multi selects or checkboxes to dis/enable elements etc.

It might not be a fair comparison but could you imagine the web without form elements? They're extremely useful (in my opinion) to stop my users entering junk

**Comment by ArktekniK** [comment]
Just spitballing, but what about an additional file that could be included that contains metadata about parameters. Means That the comment parsing doesn't need to be altered and could be detected fairly easily. Almost like a stylesheet =)

**Comment by Neon22** [comment]
its all good work.
I think it would also be useful to detect variables and present them automatically in a side panel for users to adjust using sliders or spinners. (Once the @ syntax is added and working. At least I think that was the chosen solution ?)

I keep using notepad++ but have less reason to do so every day :)

**Comment by GilesBathgate** [comment]
Another approach to the one suggested by @ArktekniK, would be to introduce a "param" keyword to denote that variables are intended to be parametric. Other markups are available such as prefixing the variables with an ```@```.

**Comment by runsun** [comment]
@t-paul 
>>> the only difference is that it's keyboard based. Any number can be changed using ALT + Cursor keys.
Aaahhh I didn't know about that. Thx. The disadvantage: it seems only works on +1, -1 level; the advantage: preview w/o the need of saving file.

**Comment by runsun** [comment]
@ArktekniK: true. I see that they serve different purposes.

**Comment by t-paul** [comment]
@runsun it adds/subtracts depending on the actual cursor position in the number, so if you have 100 and the cursor is between the two zeros, it will do +/- 10.
If you move the cursor with `ALT+RIGHT` after then end of the number, it will automatically add decimals.

**Comment by runsun** [comment]
@t-paul That's brilliant. Thx for sharing.

**Comment by kintel** [comment]
I believe this has been fixed.
@o-jasper Have you given this a spin? It's available in our development snapshots.
@amarjeetkapoor1 Want to claim the bounty?

**Comment by amarjeetkapoor1** [comment]
Ok! Yeah sure.  Just one thing, how may one go about claiming a bounty? Guide.

**Comment by kintel** [comment]
@amarjeetkapoor1 There should be somewhere to click inside Bountysource to tag a feature as done. The backers can then release the funds.

**Comment by amarjeetkapoor1** [comment]
It says:

`You will be able to claim this bounty as soon as the original issue is marked as closed. `

So, I guess. I could only claim it after this issue is closed.

**Comment by nophead** [comment]
You have to sign up to Bountysource and specify a commit that implements the feature. Then the issue needs to be closed by the original poster I think.

I am trying to claim my own bounty for #149 but the issue was opened by @daid, not me.

**Comment by daid** [comment]
(That's easy to solve ;-) I didn't check if it was actually fixed now. But it's a pretty old issue from me. And I trust you)

**Comment by nophead** [comment]
Thanks. It's fixed in master but not in a release yet. I will update the documentation when it is.

**Comment by t-paul** [comment]
Closing as discussed above. @amarjeetkapoor1 please try again with bounty source.

**Comment by amarjeetkapoor1** [comment]
I have submitted the claimed on bountySource
