### ISSUE TITLE
Decompose objects into volumes before exporting

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#732]
This issue has change into being about discussing volume decomposition on export, see the comment from @OskarLinde below.

Old:

Either the check is broken or the geometry is...
![chech validity no](https://cloud.githubusercontent.com/assets/1972961/2562871/7b01bf62-b864-11e3-8747-e7b0dcbd596c.JPG)
##

**Comment by kintel** [comment]
1. in the comment from @OskarLinde has been implemented. 2. is still interesting. @OskarLinde If you have any code for doing that, in OpenSCAD or stand-alone, I'd be interested.

**Comment by kintel** [comment]
I'm closing this, as our latest iteration of exporters now use an indexed PolySet implementation, where vertices belonging to different volumes have been duplicated. This works nicely for the Manifold backend. There may still be some corner cases for CGAL, but since this ticket is getting old, it's probably better to open new tickets for current issues.
