### ISSUE TITLE
toString and toInt

### ISSUE THREAD

**Issue by filipbys** [openscad/openscad#877]
Having the capability of converting numbers to strings and back would be enormously helpful. Thanks!
##

**Comment by MichaelAtOz** [comment]
I got back here from a search,  and was about to close this issue, but...

I was looking for some decimal to hex (as string) code in the search, so now I wonder if we should have some other built-in string to number function(s)? Save reinventing the wheel.
??

**Comment by doug-moen** [comment]
@MichaelAtOz: Converting a string to an integer is fairly easy to code in OpenSCAD (as you recently demonstrated).

However, converting a decimal string, with optional decimal place and exponent, to a floating point number, is very difficult to do, if you want the code to be accurate and correct. I wouldn't want to implement this in OpenSCAD. It would be reasonable to provide a strtonum(str) function, which is a wrapper around the C library function strtod().

The C function strtol() looks for an initial "0x" or "0X" prefix, and if it exists, then it interprets the string as a hexadecimal integer. You could incorporate that behaviour into the OpenSCAD strtonum() as well.

**Comment by kintel** [comment]
Should be fixed by #2509

**Comment by MichaelAtOz** [comment]
> Should be fixed by #2509

That provides `ord()` & enhanced `for`, that could simplify a userspace `str2num(str)`, but this issue is proposing a built-in one for consistency, rather than the proliferation of user solutions to a common problem. Doug's suggestion is just to wrap C's `strtod()`.

i.e. we have `str(num)` we need the opposite direction. Much as we had `chr()` so needed `ord()`.

If you want syntactical symmetry, it should presumably be called `num(str)`.

**Comment by MichaelAtOz** [comment]
Floating point & exponents?

**Comment by MichaelAtOz** [comment]
;)

**Comment by t-paul** [comment]
Well, that would be `toDouble()` which is not mentioned anywhere. But I guess that or `num()` is at least open for discussion. I certainly agree with @doug-moen that implementing a full parser as user space feels wrong.
