### ISSUE TITLE
Issue warning when exporting potentially non-manifold geometry

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#925]
After merging #337, there is a risk that we export non-manifold meshes due to conversion from CGAL's high precision numbers to doubles. We should add an analysis step for the PolySet mesh before export and warn the user of any problems.

**Comment by laird** [comment]
I am getting many generated STLs that are non-manifold. For example: https://drive.google.com/file/d/0Bx0lyF8Q_TkcN1F2a3lVdjF1YW8/view?usp=sharing .

I'm still digging into it, so I don't have a simple source file to share yet, but I wanted to report it because I never saw bad STLs generated by OpenSCAD with the older (pre-editor) versions of OpenSCAD. So far I'm seeing it with code that does 'difference' quite often, but not with code that just does union, translate, and scale.

I'll keep digging, but I'm sharing the STL in case it provides any clues. NetFabb reports holes, identical triangles, etc.

Preview in OpenSCAD (with no 'shimmer' from coplanar surfaces, etc.).

![screen shot 2015-02-10 at 8 08 32 am](https://cloud.githubusercontent.com/assets/768147/6127711/12b78554-b0fc-11e4-8b44-faa4d5d76120.png)

NetFabb hilighting a problem: 

![screen shot 2015-02-10 at 8 05 16 am](https://cloud.githubusercontent.com/assets/768147/6127687/b8f0cc24-b0fb-11e4-8eb5-b944202ad0a7.png)

And causing my slicer (S3D) to lose its mind:

![screen shot 2015-02-10 at 7 55 52 am](https://cloud.githubusercontent.com/assets/768147/6127691/dc609d74-b0fb-11e4-8914-2392b3563d5f.png)

I'll work on creating a minimal case that I can share.

**Comment by kintel** [comment]
I also see non-manifold edges in that STL. Please share some .scad examples as soon as you can so we can get to the bottom of this.

**Comment by laird** [comment]
Here's the script:

//seed = floor(rands(0,65535,1)[0]);
seed=19;
echo("Seed ",seed);

seeds=rands(1,65536,5, seed);

scale=rands(0.5,2,1, seeds[0])[0];
echo("scale",scale);

r=rands(7.5,10,6, seeds[1]);
minr = min(r);
maxr = max(r);

h=rands(maxr*1.3,maxr*1.3+3,6, seeds[2]);
s=rands(3,8,6, seeds[3]);
e=rands(1,100,6); // generate effect for special sides
xa=[0,90,180,-90,0,0];
ya=[0,0,0,0,90,-90];

minx = -h[5];
maxx = h[4];
sizex = maxx-minx;

miny = -h[1];
maxy = h[3];
sizey = maxy-miny;

minz = -h[2];
maxz = h[0];
sizez = maxz-minz;

vol = sizex*sizey*sizez*scale*scale*scale;
points = floor(log(2,vol))-10;
//echo(sizex,sizey,sizez,vol,points);



echo("Points",floor(log(2,vol)-10));

min = min(-minx,maxx,-miny,maxy, -minz, maxz);
max = max(-minx,maxx,-miny,maxy, -minz, maxz);

//echo(str("x ",minx,"-",maxx," y ",miny,"-",maxy," z ".minz,"-",maxz," h ",min,"-", max," r ", minr,"-", maxr));

//%translate([minx,miny,minz]) cube([maxx-minx,maxy-miny,maxz-minz], center=false);

module dieShape(out=0, label=0) {
    //hull() 
    for (i=[0:5]) {
        height = max(maxr,h[i]);
        //echo("height",height);
        //echo(str(i,") xa ",xa[i],", ya ",ya[i]," r ",r[i]," h ",h[i]," height ", height, " sides ", i+3));
        //color([xa,ya,h,r]) 
        rotate([xa[i],ya[i],0]) {
            if (!label) cylinder(r=r[i],h=h[i]+out, $fn=4);//i+3);
            else translate([0,0,h[i]+out-.99]) resize([r[i],r[i],1]) effect(e[i]);
            }
        }
    }
    
union(convexity=20) {
    scale(scale, convexity=20) {
        hull(convexity=20) dieShape(0);
        difference() {
            dieShape(.5);
            dieShape(label=1, out=1);
            }
        color("grey") intersection(convexity=20) {
                hull(convexity=20) dieShape(.5);
                union(convexity=20) {
                    rotate([45,45,0]) nums();
                    rotate([-45,-45,0]) nums();
                    rotate([45,-45,0]) nums();
                    rotate([-45,45,0]) nums();
                    }
                }
            }
        }

module nums() {
    num();
    rotate([180,0,0]) num();
    }

module num() {
    resize([sizex/4,sizey/4,sizez/2+5]) linear_extrude(1) text(str(points), halign="center", valign="center");
}

module write(l) {
    echo(str("Effect: ",l));
    linear_extrude(2) text(l, halign="center", valign="center");
    }

// write label of special effect
module effect(e) {
    //echo("Effect",e);
    if (e<10) write("X");
    else if (e<30) write("+1");
    else if (e<40) write("+2");
    else if (e<50) write("-1");
    else if (e<60) write("-A");
    else if (e<70) write("!");
    else if (e<80) write("@");
    else if (e<90) write("#");
    else if (e<95) write("$");
    else write("?");        
    }

/*
cylinder(r=10,h=15,$fn=6);
rotate([180,0,0]) cylinder(r=10,h=15,$fn=6);
rotate([90,0,0]) cylinder(r=10,h=15,$fn=6);
rotate([-90,0,0]) cylinder(r=10,h=15,$fn=6);
rotate([0,90,0]) cylinder(r=10,h=15,$fn=6);
rotate([0,-90,0]) cylinder(r=10,h=15,$fn=6);
*/

**Comment by laird** [comment]
Thinking about it, the bug is that invalid geometry is invalid. Either my math/logic is right and there's a bug in creating the STL, or my math/logic is wrong and OpenSCAD should refuse to generate the invalid result. :-)

**Comment by kintel** [comment]
Corner cases are hard. In general, my goal is that _if_ we successfully export an STL, it should be a valid closed mesh. Sometimes, this means weakly manifold, but dangling edges is not good.

**Comment by kintel** [comment]
Minimal example slimmed down from above:
```
module dieShape(out) {
  rotate([-90,90,0]) cylinder(r=10,h=15+out, $fn=4);
  rotate([0,-90,0]) cylinder(r=10,h=15+out, $fn=4);
  rotate([0,0,0]) cylinder(r=10,h=15+out, $fn=4);
}
    
hull() dieShape(0);
dieShape(.5);
```

**Comment by kintel** [comment]
This will be handled as part of #1215 from now
