### ISSUE TITLE
Change in scale/size in viewport (or distance= wrong)

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#932]
Comparison of 2014.03 & 2014.09.03 (same with 2014.07.nn), both with Reset View then zoomed to ~ equal distance= values.
![distance off](https://cloud.githubusercontent.com/assets/1972961/4144065/a77bddae-33d7-11e4-8684-726ef47d13d6.JPG)
##

**Comment by thehans** [comment]
I think camera settings have changed a few times since this was opened.
At a distance of ~11, the nightly looks more similar to the original left example than the right.
Also note that the view scaling is based on the height of the pane, so taller aspect ratio will fill more of the screen at a given distance.

I don't think there is any action to be taken on this any longer, closing.
